= NetSuite Reference

Whether you are using NetSuite as a data source (take a new NetSuite contact and copy it to Salesforce for example) or a data target (when
a Salesforce opportunity closes, create a Netsuite sales order), the details of how to work with data in a flow are specific to the data source or data target.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
You must connect to NetSuite as a regular user (WSU), not a concurrent user (cWSU).

Account::

The account ID as listed in your NetSuite instance by accessing *Setup > Integration > SOAP Web Services Preferences*. The value is a string of letters and numbers, for example: `TESTME1234567`.

Consumer Key::

The consumer key generated in NetSuite by accessing *Setup > Integration > Manage Integrations*

Consumer Secret::

The consumer secret generated in NetSuite along with the consumer key

Token ID::

The token ID generated in NetSuite

Token Secret::

The token secret generated with the token ID in NetSuite

== Triggers

include::_partials/trigger-definition.adoc[]

New record::

A new record is created in NetSuite.

New/updated record::

A record is created, or an existing record is updated.

== Actions

include::_partials/action-definition.adoc[]

Search record::

Find and retrieve a record based on search criteria.

Create record::

A record is created.

Update record::

A record is changed.

Upsert record::

A record is created or changed.