= Xero Connector Reference

Xero is a SaaS-based accounting application used primarily by small to medium sized businesses for accounting functions such as invoice creation and tracking, receiving and tracking payments, managing inventory, storing customer contacts, and creating purchase orders and quotes.

== Connections

include::_partials/connection-definition.adoc[]

To establish a connection from Composer to Xero, you must select the Xero organisation to which you want to connect in the *Organisation* field.

include::_partials/connection-name.adoc[]

Username::

The OAuth username that you use to log in to Xero.

Password::

The OAuth password that you use to log in to Xero.

== Triggers

include::_partials/trigger-definition.adoc[]

New/updated Contact::

Checks for a new or updated contact record. Provide a value for the following fields:

* *Contact Type*
* *Organisation*

New/update item::

Checks for a new or updated item record. Provide a value for the following fields:

* *Is purchased*
* *Is sold*
* *Is tracked as inventory*
* *Organisation*

New payment::

Checks for a submitted payment. Provide a value for the *Organisation* field.


== Actions

include::_partials/action-definition.adoc[]

Create or update contact::

Creates a new contact record nor updates an edisting contact record. Provide a value for the following fields:

* *Contact type*
* *Organisation*
* If you add additional contacts, you must also provide a value for *Email address*.

Search contact::

Returns a list of contact records based on values entered. Provide a value for *Organisation*.

Get contact by ID::

Returns a single contact record based on the ID value. Provide a value for the following fields:

* *Contact ID*
* *Organisation*

Create or update invoice::

Creates an invoice record. Provide a value for the following fields:

* *Organisation*
* *Invoice type*
* *Contact name*
* *Items*


Update invoice headers::

Updates specific fields in an invoice record. Provide a value for the following fields:

* *Invoice Reference Type*
* *Invoice Reference*
* *Organisation*

Create or update item::

Creates or updates a field in the item record. Provide a value for the following fields:

* *Item Code*
* *Organisation*

//Create Item::
//Creates an item record. Provide a value for Item Code. Additionally, if a value is specified in the Inventory Asset Account Code field, then a value is required in the Purchase Account Code field.

== Objects

The following object types are available:

* Action: *Create or update invoice*
* Field: *Contact persons*
