= Google Sheets Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Connection Details

Google Account::

If you are already logged in to a Google account, you'll be asked to approve access.

//TODO: what if not already logged in?

== Triggers

New spreadsheet::

This trigger fires when a new spreadsheet is created in the Google drive associated with the connection.
//TODO: What about a new sheet? Use case is send a slack message each time.

New row in sheet::

This trigger fires when a new row is added to the end of one sheet within a spreadsheet identified in the connection.

The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.
Each time the flow is triggered after the first, new rows added at the end of the sheet are picked up every five minutes.
//TODO: post-GA webhook allows for actual real-time pickup

New or updated row in sheet::

This trigger fires when a sheet is created or updated.

The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.

Each time the flow is triggered after the first, new rows added at the end of the sheet are picked up every five minutes.

=== Limits

* Sheets limited to 10,000 rows
* Header rows excluded
* Trigger works with My Drive, not Team Drive


== Actions

Create a spreadsheet row::

Adds a new row at the end of the sheet named in the connection.

Update a spreadsheet row::

Update a row in a sheet.

//TODO: How does this work if "search rows" is post-GA?

=== Limits

* Sheet must have a header row. If data is stored in row #1, the action fails.

== Example