= Tableau Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Connection Details

Tableau server URI::

The URL where you usually log in, for example: `http://MyServer/api/3.8/auth/signin`

Token name::

The personal access token that you created in Tableau's Account Settings page

Token secret::

The secret for the personal access token

Site::

The site attribute (also called a Site ID), the subpath of a site's full URL in
Tableau

The Site ID is the first portion of the URL that appears after `/site` in the browser URL bar after you log in. If you are connecting to Tableau Online, this value is required.

For example, if you see `https://10ay.online.tableau.com/#/site/MarketingTeam/workbooks` in your browser URL, then the *Site* value is `MarketingTeam`.

For more information about authentication in Tableau, see `https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm`.

=== Duration of Tokens

Tableau has limits on personal access tokens that affect your connection:

* Any token not used in 15 days is revoked. If you fail to exercise a connection in 15 days, you'll need to create a new one.
* All personal access tokens are revoked after one year. You can add an expression to account for this.
//TODO Get details from Gaston

== Triggers

You must use *Scheduler* for Tableau. Event triggers are not available.

== Actions

Add Data to Data Source::

Add new data to an existing Tableau data source instead of creating a new data source.

Required values:

* *Project*
* *Data Source*

The data structure and optional fields, if specified previously (TODO: Where?), are listed and cannot be changed.

//TODO: What does it mean "they can be deleted to hide them in the form, and this won't change structure of data source"?

== Example
