= Tableau Connector Reference

Use Tableau as a data target. For example, you can push Salesforce data to an existing Tableau hyper file.
Some details of how to work with data in a flow are specific to the data target.

== Tableau Requirements for Composer

* You can connect to Tableau Online or Tableau Server.
* Your instance of Tableau must be publicly internet-facing and be version 2019.4 or higher.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Tableau server URI::

The URI is the domain where you usually log in, for example, `\https://[region].online.tableau.com`

Token name::

The personal access token that you created in the Tableau Account Settings page

Token secret::

The secret corresponding to your *Token name*

Site::

The site attribute, also called a Site ID
+
This is the first portion of the URL that appears after `/site` in the browser URL bar after you log in. If you are connecting to Tableau Online, you must supply the site attribute.
+
For example, if you see `\https://10ay.online.tableau.com/#/site/MarketingTeam/workbooks` in your browser URL, the *Site* value is `MarketingTeam`.

For more information about authentication in Tableau, see `https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm`.

=== Limitations

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error will occur.
//CCONN-714, copied from tableau reference

=== Duration of Tokens

Tableau has limits on personal access tokens that affect your connection:

* Any token not used in 15 days is revoked. If you fail to exercise a connection in 15 days, you'll need to create a new token.
* All personal access tokens are revoked after one year. You can add an expression to account for this.

//TODO Get details on "expression-to-stop-revocation" from Gaston

== Triggers

You must use a scheduler or other connector for a flow that includes Tableau. Event triggers are not available.

== Actions

include::_partials/action-definition.adoc[]

Add Data to Data Source::

Add new data to an existing Tableau data source.
+
* You must specify two pieces of information for each data source: the Tableau project ID and data source ID, which you can retrieve from the URL of the open project and data source, respectively. Once entered, Composer displays the project name and data source name instead of the IDs.
* The data source you use must be published and must connect live to a hyper file.
+
You can create a hyper file using Tableau Desktop (*Connect To a File -> _hyper-file name_*) or by publishing a `.hyper` file via the REST API or `tabcmd`. You can't access a live data source such as a CSV or Excel file, nor can you access data sources that are refreshed on a recurring basis per a schedule defined in Tableau.
* The time it takes for changes made by the flow to show up in Tableau servers depends on the size of the hyper file.

If the data source that you are populating has a `Time` field but does not include a date, then Tableau stores the date value in the data source as `30/12/1899`.

include::_partials/see-also.adoc[]
