= Salesforce Reference

Whether you are using Salesforce as a data source (take new Salesforce records and copy them to a Google Sheet, for example) or a data target (take a Google Sheet row and turn it into a Salesforce lead), some details of how to work with data in a flow are specific to the data source or data target.

== Salesforce Sandbox and Production Orgs

You can connect to both sandbox and production orgs.
For the best protection:

* Connect to a sandbox org when you build and test a flow.
* After testing is complete, connect to a production org, test, and then activate the flow.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Username and password::

The username and password that you used to log in to Salesforce.
You'll need to create a connection even if the data source is the same Salesforce org
where you operate Composer.
However, Composer won't ask for your password again. Instead, it displays an authentication approval dialog.

URL::

The URL that you used to log in to Salesforce, for example, `myOrg.salesforce.com`.

=== Salesforce Connected App Limits

Salesforce allows each user to grant access to no more than five connected apps at a time.
Because of this limit, if you create more than five Composer connections to the same Salesforce org, Salesforce
revokes tokens from the oldest to the most recently created, without notice, until the number of authorized tokens returns to five.

If possible, create only one connection per user per Salesforce org to avoid this issue.

For more about Salesforce connected apps and authorization, see https://help.salesforce.com/articleView?id=remoteaccess_request_manage.htm.

== Triggers

include::_partials/trigger-definition.adoc[]

New record::

Checks for a new record every 10 minutes.

New or updated record::

Checks for new or updated records of the specified object type every 10 minutes.

Deleted record::

* Checks for a deleted record every 30 minutes.
* Returns only soft-deleted records. Soft-deleted records are stored in Salesforce for approximately 15 days.
+
Records are typically stored for approximately 15 days before being hard-deleted and irretrievable.
* You can't modify the soft-delete timestamp.

== Actions

include::_partials/action-definition.adoc[]

Create new record::

Create a standard or custom record.

Update record::

Update any standard or custom record as specified by record ID.

Get records::

Return all the records that match specified search terms.

Create or update record::

Update any standard or custom record as specified by record ID.
If the record ID isn't found, create the record.

Delete record::

Delete a record specified by its object type and record ID.
