= Workday Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Tenant Name::

The name or ID of your Workday tenant
+
For example, if the URL where you log into WorkDay is `na.workday.com/wday/authgwy/global-modern/`, then your tenant name is `global-modern`.

User Name and Password::

The username and password that you use to log in to the system

== Triggers

New or updated object::

This trigger checks for a new or updated object.


== Actions

Get Worker Details by ID::

This action returns the worker details corresponding to the employee's `Workday ID` that you supply.

Create Worker::

This action creates a new worker.

Update Job Requisition::

This action updates the details on a job requisition.

Get Customer::

This action returns the customer details corresponding to the customer ID that you supply.

== Object Types

The following object types are available:

* Triggers
    ** JOB_REQUISITIONS
    ** WORKER

* Actions
    ** CUSTOMER
    ** JOB_REQUISITIONS
    ** WORKER

