= NetSuite Reference

Whether you are using NetSuite as a data source (take a new NetSuite contact and copy it to Salesforce, for example) or a data target (when a Salesforce opportunity closes, create a Netsuite sales order), the details of how to work with data in a flow are specific to the data source or data target.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
You must connect to NetSuite as a regular user (WSU), not a concurrent user (cWSU).

include::_partials/netsuite-connection-details.adoc[]

=== Establish a NetSuite Connection

To use MuleSoft Composer to establish a NetSuite connection, you must have:

* The MuleSoft Composer User permission set to `perform integration tasks`.

* An account in Salesforce to store the internal ID of the associated customer in NetSuite. You must ensure that a custom field, NetSuite ID, has been created for the Account object in the organization.

== Triggers

include::_partials/trigger-definition.adoc[]

On Updated Records::

A record is created, or an existing record is updated.

On New Records::

A new record is created in NetSuite.

== Actions

include::_partials/action-definition.adoc[]

Update Record::

A record is changed.

Create Record::

A record is created.

Upsert Record::

A record is created or updated.

Delete Record::

A record is deleted

== Record Types

The following record types are supported.

* Triggers

** Contact
** Customer
** Employee
** Inventory Item
** Invoice
** Sales Order
** Support Case


* Actions
+
The following record types are valid for all actions:

** Contact
** Customer
** Customer Refund
** Employee
** Inventory Item
** Invoice
** Payment Item
** Sales Order
** Support Case

== Custom Objects and Custom Fields

Custom objects and custom fields are not supported.

== List Objects

List objects are supported.
