= Workday Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Connection Details

Connection Name::

The name you assign to this connection
+
Give your connection a name that will help you recognize it later on,
since none of the details except the name will be visible after you create it.

Tenant Name::

The name or ID of your Workday tenant

<<<<<<< HEAD
User Name and Password::
=======
Username and Password::
>>>>>>> ea372a72aa4e6e7708f07d934c41bc8a7d4ac3e9

The username and password that you used to log in to the system

== Triggers

New or updated object::

This trigger checks for a new or updated object.

You specify the object type:

* *JOB_REQUISITIONS*
* *WORKER*

== Actions

Get Worker Details by ID::

This action returns the worker details corresponding to the ID that you supply.

Create Worker::

This action creates a new worker.

Update Job Requisition::

This action updates the details on a job requisition.

Get Customer::

//TODO: Description--how does the flow know which customers to return? or does it return all?


== Example
