= MuleSoft Composer for Salesforce Glossary

connection::

The credentials that give you access to a system where you want to access data: the username, password,
and URL where you send these credentials to gain access.

flow::

All the work and data structures needed to complete an automated process:

* *trigger*: The event or time that, when it occurs, tells the flow to start doing its work.
* *action*: Something you do with, or to, the data fetched from a connection.
* *data structure*: The metadata or other definitions that control how your data is stored in a system. For example, Salesforce stores data in sObjects and fields, and Google Sheets stores information in sheets, rows, and cells. Data or values are stored in the smallest unit of data structures.
* *logic*: The circumstances or requirements that must be met before an action is taken. Conditional logic consists of if/else statements or for-each statements.
* *step*: A trigger or action, and the conditional logic needed to decide whether to take the step or skip it. A step optionally includes a connection different from the initial trigger, depending on the work being done.

system::

Any source of data that Composer can connect to in order to run a flow.
