= Slack Reference

When you use Slack as a data target (such sending a Slack message when a Salesforce opportunity is won), some details of how to work with data in a flow are specific to Slack.

== Connection Details

include::_partials/connection-definition.adoc[]

Workspace Name:

Enter your workspace name, for example `my-workspace.slack.com`.

Username and password::

The username and password that you use to log in to Slack.

== Triggers

Use Scheduler to specify when a flow is triggered, for example every fifteen minutes.

You can't trigger a flow using a connection to Slack.

== Actions

include::_partials/action-definition.adoc[]

Post Message to Channel::

Post a new message to a specific private or public channel that you select.
Type the channel into the field using the format: `#my-channel-name`.

Send Direct Message::

Post a direct message to the specified user by typing it into the field.

Find User by Email Address::

Find a user by typing their email address into the field.
