= Slack Reference

When you use Slack as a data target (such sending a Slack message when a Salesforce opportunity is won), some details of how to work with data in a flow are specific to Slack.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name::

The Slack workspace name, for example, `my-workspace.slack.com`.

Username and password::

The username and password that you use to log in to Slack.

== Triggers

Use Scheduler to specify when a flow is triggered, for example every fifteen minutes.

You can't trigger a flow using a connection to Slack.

== Actions

include::_partials/action-definition.adoc[]


Send a direct message to a user::

To post a direct message to a specified user, supply the following information:
+
* *User*: the user to receive the message. *(If I add the Name data pill from Salesforce opportunity, how is that mapped to a slack username?)*
* *Message*: The message to be sent.
* *Bot Name*: Be default, the sender of Slack messages generated by an action is "MuleSoft Composer." You can supply a different name here for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is "MuleSoft Composer," along with the MuleSoft logo. You can supply a different logo for the messages sent by this action. Specify an icon URL whose access is not restricted.

Create a message::

Post a new message to a specific private or public channel that you select.
+
* *Channel Name*: A channel name in the format `#my-channel-name`.
* *Message*: The message to be sent.
* *Bot Name*: By default, the sender of Slack messages generated by an action is "MuleSoft Composer." You can supply a different name for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is "MuleSoft Composer," along with the MuleSoft logo. You can supply a different logo for the messages sent by this action. Specify an icon URL whose access is not restricted.

Find User by Email Address::

Find a Slack user by entering their email address into the *Email* field.

[TIP]
If you don't have Slack user email addresses in the data returned by your trigger, you can insert this action after the trigger, in order to fetch the Slack user by an email address from another system.