= Release Notes for MuleSoft Composer for Salesforce

Use MuleSoft Composer for Salesforce to build connected experiences faster. You don't need to wait for development resources to unlock data, integrate apps, and automate business processes that create real customer value.

New versions are automatically available once they are released; you don't need to perform any tasks to move to the new version.


== July 8, 2021

=== New Features

You can now connect to a new system: Xero.

See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== JIRA

* The following standard fields are not supported at this time:

** *Affects version*
** *Fix version*
** *Environment*
** *Component*

* Custom fields containing the following list components are failing to render:

** *Text field (multi-line)*
** *Labels*
** *Checkboxes*
** *Radio Buttons*
** *Select list (multiple-choice)*
** *Select list (cascading)*

* In the *Status* field, the *In Progress* value sometimes appears twice. If so, please test both *In Progress* values to find the working value.

* After creating a case in JIRA, the *Update issue* action does not update the value in the *Reporter* field. Additionally, the value in this field must be blank for the *Update issue* action to succeed. To update the value in the *Reporter* field, you can manually update the case record in JIRA.

* If custom fields fail to appear, reset your JIRA connection by deleting the connection and re-authenticating your JIRA account.

* When you create an issue, you may encounter a 400 error in the output metadata. Please disregard this error.

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== July 1, 2021

=== New Features

* You can now connect to a new system: JIRA.
+
See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

* The NetSuite connector now supports Custom Record Types for actions and triggers.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== JIRA

* The following standard fields are not supported at this time:

** *Affects version*
** *Fix version*
** *Environment*
** *Component*

* Custom fields containing the following list components are failing to render:

** *Text field (multi-line)*
** *Labels*
** *Checkboxes*
** *Radio Buttons*
** *Select list (multiple-choice)*
** *Select list (cascading)*

* In the *Status* field, the *In Progress* value sometimes appears twice. If so, please test both *In Progress* values to find the working value.

* After creating a case in JIRA, the *Update issue* action does not update the value in the *Reporter* field. Additionally, the value in this field must be blank for the *Update issue* action to succeed. To update the value in the *Reporter* field, you can manually update the case record in JIRA.

* If custom fields fail to appear, reset your JIRA connection by deleting the connection and re-authenticating your JIRA account.

* When you create an issue, you may encounter a 400 error in the output metadata. Please disregard this error.

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== June 4, 2021

=== New Features

You can now connect to a new system: Microsoft Teams.

See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== June 2, 2021

=== New Features

You can now connect to two more systems: Asana and Twilio.

See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== May 19, 2021

=== New Features

You can now connect to a new system: Stripe.

See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If a NetSuite data pill is used in a Slack message that also contains text, testing fails for the NetSuite to Slack flows.
//CPLAT-1288

* If a user has not completed any field mappings in the NetSuite *Update Record* action, then testing will not start.
//CPLAT-1292

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== May 6, 2021

=== New Features

You can now expand all cards or collapse all cards on the canvas using the *Expand all* or the *Collapse all* button.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If a NetSuite data pill is used in a Slack message that also contains text, testing fails for the NetSuite to Slack flows.
//CPLAT-1288

* If a user has not completed any field mappings in the NetSuite *Update Record* action, then testing will not start.
//CPLAT-1292

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== April 29, 2021

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If a NetSuite data pill is used in a Slack message that also contains text, testing fails for the NetSuite to Slack flows.
//CPLAT-1288

* If a user has not completed any field mappings in the NetSuite *Update Record* action, then testing will not start.
//CPLAT-1292

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== April 13, 2021

=== New Features

You can now connect to two more systems: Slack and NetSuite.

See xref:ms_composer_reference.adoc[the product documentation] for details about each connector.

* The user interface for creating a connection is easier to understand.

=== Known Issues

The following issues were identified at the time of this release:

* If you select the *Create Message* action in Slack, only public channels are returned.
//CCONN-765

* If a NetSuite data pill is used in a Slack message that also contains text, testing fails for the NetSuite to Slack flows.
//CPLAT-1288

* If a user has not completed any field mappings in the NetSuite *Update Record* action, then testing will not start.
//CPLAT-1292

* If you see the "Already editing somewhere?" dialog, but you aren't editing the flow in another tab, log out of Composer and log back in to resume work.
//CAPO-47

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

* As part of the Salesforce action *Get records*, you can't query based on a Date field.
//CPLAT-1126

* Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error occurs.
//CCONN-714, copied to Tableau reference

== March 25, 2021

=== New Features

You can delete and replace a trigger step in any unactivated flow.

=== Known Issues

The following issues were identified at the time of this release.

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

* You can't access the *Add Connection* button from a trigger or action once it has been created.
+
To change a connection to a new connection of the same system type:
+
. Add an action to the end of your flow, which displays the *Add Connection* button.
. Create your new connection.
. Delete the action you added.
. In the trigger or action where you want to change to the new connection, click the change icon (three dots).
. Click *Change Connection*. The new connection is listed.

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

* As part of the Salesforce action *Get records*, you can't query based on a Date field.
//CPLAT-1126

* Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error will occur.
//CCONN-714, copied to Tableau reference

== March 15, 2021

MuleSoft Composer for Salesforce is generally available.

=== Known Issues

The following issues were identified at the time of this release.

* If you don't see the *New Flow* button on the Recently Viewed list page, switch to the All list page.
//CAPP-1625

* If you see a blank area instead of the Home page contents when you first log in to Composer, clear your browser cookies and reload.
//CAPP-2051

* You can't access the *Add Connection* button from a trigger or action once it has been created.
+
To change a connection to a new connection of the same system type:
+
. Add an action to the end of your flow, which displays the *Add Connection* button.
. Create your new connection.
. Delete the action you added.
. In the trigger or action where you want to change to the new connection, click the change icon (three dots).
. Click *Change Connection*. The new connection is listed.

* After you create a trigger, you can't delete that step.
+
To change to a new connection on a trigger that has already been created, use one of the following workarounds:
//CAPP-1550
+
** If you want to change the data source, for example switching from Salesforce to Workday, create a new flow.
** If you want to change the instance of the same data source, but the connection for that source doesn't exist yet:
+
. Add an action to the end of your flow. In the action, create the connection you need.
. Delete the action.
. Open the trigger and use *Change Connection* to change to the new connection.

==== Google Sheets

A space in the name of your Google Sheet worksheet can cause an error during testing. Remove the space and rerun the test.
//CCONN-735

==== Salesforce

* As part of the Salesforce action *Get records*, you can't query based on a Date field.
//CPLAT-1126

* Composer doesn't set the value of some required Boolean fields on the User object. You must set these values in the relevant step.
//CAPP-2009

==== Tableau

Only one flow can append to the same Tableau data source. If more than one flow or app outside of Composer accesses the data source at the approximate same time, a Composer error will occur.
//CCONN-714, copied to Tableau reference
