= MuleSoft Composer for Salesforce Prerequisites

You must have the correct Salesforce edition and have access to MuleSoft Composer for Salesforce (Composer) in your Salesforce org.

== Salesforce Requirements

To activate Composer in Salesforce:

* Use a Salesforce Unlimited, Enterprise, or Performance edition
* Enable Lightning
* Purchase the separate MuleSoft Composer license

== Verify Access to Composer

To use Composer, verify that you have access to the Composer app:

. In your Salesforce org, open the App Launcher.
. Enter *composer* in the search bar.
. Select *MuleSoft Composer* from the search results.
+
If you don't see *MuleSoft Composer* in the search results,
it's likely that you need to purchase Composer for your Salesforce org or that you don't have permission to access it.

When the Composer page displays, you're ready to create your first flow.

== Next Steps

If you're not sure you are ready to start, you can learn more about how to connect your systems and data:

* The other topics in this section.
* Trailhead module 1 TODO: **link** JIRA created for this
* Trailhead module 2 TODO: **link** JIRA created for this
