= MuleSoft Composer for Salesforce Glossary

connection::

The credentials that give you access to a system where you want to access data: the username, password,
and URL where you send these credentials to gain access.

data structure:: The metadata or other definitions that control how your data is stored in a system. For example, Salesforce stores data in sObjects and fields, and Google Sheets stores information in sheets, rows, and cells. Data or values are stored in the smallest unit of data structures. Flows move data (values in a field or cell) and data structures (including fields, cells, rows, and tables).

flow::

All the work and data structures needed to complete an automated process:

* *action*: Something you do with, or to, the data fetched from a connection.
* *step*: A trigger, or one or more actions. Steps include the logic needed to decide whether to perform the step or skip it. A step optionally includes a connection different from the initial trigger.
* *trigger*: The event or time that, when it occurs, tells the flow to start doing its work.
+
The first step of every flow is a trigger or scheduler.

logic::

The circumstances or requirements that must be met before an action is taken: if/else statements or for-each statements. Insert logic into steps as needed to ensure actions are taken only on the data that should be acted on, not on all the data returned.

system::

Any source of data that Composer can connect to in order to run a flow.
