= Twilio Reference

Twilio is a SaaS cloud communications platform that allows users to make and receive phone calls, send and receive text messages, and perform other communication functions using web service APIs.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Account SID::

The Account SID that you use to log in to Twilio.

Auth Token::

The Auth Token that you use to log in to Twilio.

== Triggers

include::_partials/trigger-definition.adoc[]

<Field>::

<Details>.

== Actions

include::_partials/action-definition.adoc[]

Send Message::

Send a message to a recipient. Values are required in the following fields:

* To
+
The value in this field must be the phone number in E.164 format, SIP address, or channel user address (such as Whatsapp or Facebook messenger channel) of the recipient and the message initiator.

* From
+
The value in this field must be the phone number in E.164 format, SIP address, or channel user address (such as Whatsapp or Facebook messenger channel) of the recipient and the message initiator.

* Message Text
+
The value in this field cannot exceed 1600 characters.

* Media URL
+
If a value in this field is required to send a media message. You can only send images in SMS messages in the United States and Canada. 

== Objects

<Field>::

<Details>.
