= Google Sheets Reference

Whether you are using Salesforce as a data source (take new Google Sheet rows and copy them to a Salesforce org as Contacts, for example)
or a data target (take my new Salesforce Contact and turn it into a row in a Google Sheet),
some details of how to work with data in a flow are specific to the data source or data target.

== Connection Details

include::_partials/connection-definition.adoc

* If you are already logged in to a Google account, you'll be asked to approve access.

* If you are not already logged in to a Google account, supply the email and password you use to log in to Google Sheets, and complete the authentication dialogs.

== Triggers

include::_partials/trigger-definition.adoc

New spreadsheet::

This trigger fires when a new spreadsheet is created in the Google Drive associated with the connection.

New row in sheet::

This trigger fires when a new row is added to the end of one sheet within a spreadsheet identified in the connection.
+
* The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.
* Each time the flow is triggered after the first, new rows added to the sheet are picked up every five minutes.
//TODO: post-GA webhook allows for actual real-time pickup

New or updated row in sheet::

This trigger fires when a sheet is created or updated.
+
* The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.
* Each time the flow is triggered after the first, new rows added at the end of the sheet are picked up every five minutes.

=== Limits

* Sheets limited to 10,000 rows
* Header rows excluded
* Trigger works with My Drive, not Team Drive

== Actions

include::_partials/action-definition.adoc

Create a spreadsheet row::

This action adds a new row at the end of the sheet named in the connection.

Update a spreadsheet row::

This action updates a row in a sheet.

=== Limits

A Google Sheet must have a header row. If data is stored in row #1, the action fails.
