= Salesforce Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Environments

You can connect to both sandbox and production orgs.
For the best protection, connect to a sandbox org when you build and test a flow, then connect to a production org to activate the flow.

== Connection Details

Username and password::

The username and password you use to log into the system. It can be different from the admin username you use while in MuleSoft.

URL::

The URL you use to log into Salesforce, for example `myOrg.salesforce.com`.

== Triggers

A new record is created::

Checks for a new record every 10 minutes.

A record is updated::

Checks for updated records every 10 minutes.

A record is created or updated (upsert)::

Checks for created or updated records of the specified object type every 10 minutes.

A record is deleted::

* Checks for a deleted record every 30 minutes.
* Returns only soft-deleted records still stored in Salesforce.
+
Records are typically stored for approximately 15 days before being hard deleted and unretrievable.
* You can't modify the soft-delete timestamp.

== Actions

Get one or more records::

Return all the records that match specified search terms.

Create a record::

Create a standard or custom record.

Update a record::

Update any standard or custom record as specified by record ID.

Upsert a record::

Update any standard or custom record as specified by record ID.
If the record ID isn't found, create the record.

Delete a record::

Delete a record specified by its object type and record ID.
