= Tableau Reference

Whenever you use Tableau as a data target (push Salesforce data to an existing Tableau hyper file, for example)
some details of how to work with data in a flow are specific to the data source or data target.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Tableau server URI::

The URI where you usually log in, for example, `\http://MyServer/api/3.8/auth/signin`

Token name::

The personal access token that you created in the Tableau Account Settings page

Token secret::

The secret corresponding to your *Token name*

Site::

The site attribute, also called a Site ID
+
This is the first portion of the URL that appears after `/site` in the browser URL bar after you log in. If you are connecting to Tableau Online, you must supply the site attribute.
+
For example, if you see `\https://10ay.online.tableau.com/#/site/MarketingTeam/workbooks` in your browser URL, the *Site* value is `MarketingTeam`.

For more information about authentication in Tableau, see `https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm`.

=== Duration of Tokens

Tableau has limits on personal access tokens that affect your connection:

* Any token not used in 15 days is revoked. If you fail to exercise a connection in 15 days, you'll need to create a new token.
* All personal access tokens are revoked after one year. You can add an expression to account for this.

//TODO Get details on "expression-to-stop-revocation" from Gaston

== Triggers

You must use a scheduler for Tableau. Event triggers are not available.

== Actions

include::_partials/action-definition.adoc[]

Add Data to Data Source::

Add new data to an existing Tableau data source.
+
Valid data source choices:
+
* Project
* Data source

When using the Tableau connector with Composer, the data source must be a hyper file. You can create a hyper file using Tableau Desktop (*Connect To a File -> _hyper-file name_*) or by publishing a `.hyper` file via the REST API or `tabcmd`. You can't access live data sources such as a CSV or Excel file, nor can you access data sources that are refreshed on a recurring basis per a schedule defined in Tableau.

The time it takes for changes made by the flow to show up in Tableau servers depends on the size of the hyper file.
