= JIRA Connector Reference

JIRA is a powerful project management tool and ticketing system used to help users plan, track, release, and report product issues in order to improve development.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Username::

The OAuth username that you use to log in to JIRA.

Password::

The OAuth password that you use to log in to JIRA.

== Triggers

include::_partials/trigger-definition.adoc[]

New issue::

Checks for a new issue created in JIRA.

Updated issue::

Checks for updated issues in JIRA.

== Actions

include::_partials/action-definition.adoc[]

Create Issue::

Creates a new issue within the selected project. Provide a value for the following fields:

* *Project*
* *Key*
* *Summary*
* *Type*
* *Status*
* *Priority*

Update/Edit issue::

Updates specified field values. Provide a value for the following fields:

* *Project*
* *Issue ID or Key*
* *Notify Users*
* *Type*

Assign User to Issue::

Assigns a user to a specified issue. Provide a value for *Issue ID or Key*.

Add Watcher to Issue::

Adds a watcher to an existing JIRA issue. Provide a value for *Issue ID or Key*.

Get Issue::

Returns details for a specific issue. Provide a value for *Issue ID or Key*.

Add Comment::

Creates and adds a comment to an existing issue. Provide a value for the following fields:
* *Issue ID or Key*
* *Comment Text*

Get Account IDs for Users::

Returns the account IDs for the users specified in the `key` or `username` parameters. You can specify multiple `key` or `username` parameters.

== Custom Fields

Using MuleSoft Composer, you can access standard custom field values in JIRA for actions and triggers that you set in the JIRA issue.
