= Salesforce Reference

The systems you connect to require credentials that you store in a connection.
These systems provide triggers and actions specific to that system.

== Environments

You can connect to both sandbox and production orgs.

For the best protection, connect to a sandbox org when you build and test a flow. After testing is complete, connect to a production org to activate the flow.

== Connection Details

Username and password::

The username and password you use to log in to the system. These can be different from the admin username and password that you use while in MuleSoft.

URL::

The URL that you use to log in to Salesforce, for example, `myOrg.salesforce.com`.

Salesforce allows each user to grant access to no more than five connected apps at a time.
Because of this limit, if you create more than five Composer connections to the same Salesforce org, Salesforce
revokes tokens from oldest to most recently created, without notice, until the number of authorized tokens returns to five.
If possible, create only one connection per user per Salesforce org to avoid this issue.

For more about Salesforce connected apps and authorization, see https://help.salesforce.com/articleView?id=remoteaccess_request_manage.htm.

== Triggers

On new record::

Checks for a new record every 10 minutes.

On updated record::

Checks for updated records every 10 minutes.

On upserted record::

Checks for created or updated records of the specified object type every 10 minutes.

On deleted record::

* Checks for a deleted record every 30 minutes.
* Returns only soft-deleted records still stored in Salesforce.
+
Records are typically stored for approximately 15 days before being hard deleted and unretrievable.
* You can't modify the soft-delete timestamp.

== Actions

Get records::

Return all the records that match specified search terms.

Create new record::

Create a standard or custom record.

Update record::

Update any standard or custom record as specified by record ID.

Create or update record (upsert)::

Update any standard or custom record as specified by record ID.
If the record ID isn't found, create the record.

Delete record::

Delete a record specified by its object type and record ID.
