= Test a Composer Flow

By testing as you build your flow, you can ensure that each step and each field mapping in your flow is working as expected before activation. Frequent validation provides near real-time feedback about the success of your flow and enables you to fix errors as you build.

IMPORTANT: Testing processes and tests a single record. You must activate your flow to process all of your records.

When testing your flow, note the following:

* A trigger step is required.
* Testing automatically ends after five minutes if not halted by an error or manually terminated.
* The entire flow is executed and tested.

When testing your flows:

* Build your flow in a sandbox environment or organization. This allows you to test your flow using inactive accounts. When you want to activate your flow, click the change icon in the trigger or action that connects to a sandbox environment and then click xref:ms-composer-flows.adoc#change-a-connection[*Change Connection*] to change your environment to a production environment while maintaining the tested field mappings.
* Test your flows with sample or dummy records.
* Consider limiting the number of records processed if your test times. 

To test a flow:

. From the *Composer Flows* tab, click the name of the flow you want to test.
. Click *Test*. +
Composer notifies you when the test is complete. The execution results from the test appear on the card.
