= Google Sheets Reference

Whether you are using Salesforce as a data source (take new Google Sheet rows and copy them to a Salesforce org as Contacts, for example)
or a data target (take my new Salesforce Contact and turn it into a row in a Google Sheet),
some details of how to work with data in a flow are specific to the data source or data target.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
Composer launches an authentication dialog where you choose which Google Drive account you're connecting to Composer, and if you aren't already logged in, you enter a username and password.

== Triggers

include::_partials/trigger-definition.adoc[]

New spreadsheet::

This trigger fires when a new spreadsheet is created in the Google Drive associated with the connection.

[NOTE]
Google Sheets are not saved at the moment of creation. They are saved the first time they are edited. Therefore, a new spreadsheet won't trigger a flow until after it is edited and saved. However, the save date is the time of creation, not the first edit. Thus, if you create a second spreadsheet and edit it before you edit the first one, the second spreadsheet triggers a flow; the first one is ignored.

//New row in sheet::
//
//This trigger fires when a new row is added to the end of one sheet within a spreadsheet identified in the connection.
//+
//* The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.
//* Each time the flow is triggered after the first, new rows added to the sheet are picked up every five minutes.
//TODO: post-GA webhook allows for actual real-time pickup
//
//New or updated row in sheet::
//
//This trigger fires when a sheet is created or updated.
//+
//* The first time this flow is triggered, all rows from the spreadsheet are returned, except the header row.
//* Each time the flow is triggered after the first, new rows added at the end of the sheet are picked up every five minutes.

=== Limits

* Sheets limited to 10,000 rows
* Header rows excluded
* Trigger works with My Drive, not Team Drive

== Actions

include::_partials/action-definition.adoc[]

Create a spreadsheet row::

This action adds a new row at the end of the sheet named in the connection.

Update a spreadsheet row::

This action updates a row in a sheet.

=== Limits

A Google Sheet must have a header row. If data is stored in row #1, the action fails.
