= MuleSoft Composer Prerequisites

You must have the correct Salesforce edition and have access to MuleSoft Composer (Composer) in your Salesforce org.

== Salesforce Requirements

The Salesforce org where you access Composer:

* Must be a Salesforce Unlimited or Enterprise edition.
* Must have Lightning enabled.
* Must have purchased MuleSoft Composer for your Salesforce org.

== Access to Composer

To use Composer in your Salesforce org, verify that you have access to the Composer app:

. In your Salesforce org, open the App Launcher.
. Enter *Composer* in the search bar.
. Select *MuleSoft Composer* from the search results.
+
If you don't see *MuleSoft Composer* in the search results,
it's likely that you need to purchase Composer for your Salesforce org.

When the Composer page displays, you're ready to get started.

== Next Steps

Before you start, you can learn more about how to connect your systems and data:

* xref:ms_composer_overview.adoc[MuleSoft Composer Overview]
* Trailhead module 1<<link to come>>
* Trailhead module 2<<link to come>>