= Test a Composer Flow

== Test a Flow

Using Test mode as you build your flow, you can ensure that each step and each field mapping in your flow is working as expected before activation. You can test your flow as often as you like. Frequent validation provides near real-time feedback about the success of your flow and enables you to fix errors as you build.

IMPORTANT: Test mode processes and test a single record. You must activate your flow to process all of your records.

=== Notes

When testing your flow, please note the following:

* A trigger step is required. A flow with a configured trigger step is considered valid.
* Testing is limited to five minutes. Testing will end when the test has reached the time limit, an event has occurred, or when the user manually terminates the test.
* Testing deploys the underlying systems for verification.
* The entire flow is executed and tested. You cannot test a subset of cards in your Composer flow.
* One job is captured per test.
* You can open but not modify cards.

=== Recommendations

When testing your flows:

* Test as you build. Each time you initiate a test, the entire flow is tested so that you can find and fix errors efficiently.
* Build your flow in a sandbox environment or organization. This allows you to test your flow using inactive accounts. When you want to activate your flow, click the change icon in the trigger or action that connects to a sandbox environment and then click xref:ms-composer-flows.adoc#change-a-connection[*Change Connection*] to change your environment to a production organization while maintaining the tested field mappings.
* Test your flows with sample or dummy records.
* Consider limiting the number of records processed if your test times out during the *Get Records* phase. You can alter the test data or the query criteria to avoid issues.

To test a flow:

. From the *Composer Flows* tab, click the name of the flow you want to test.
. Click *Edit* from the Flow Details menu bar.
. Click *Test*  from the Flow Details menu bar to test your action or trigger. +
Composer notifies you when the test is complete. The output, errors, and execution results from the job appear on the card.

== Preparing for Activation

After you test your completed flow, you are ready to xref:ms_composer_activation.adoc[activate] it.

If you used a sandbox environment while creating and testing the flow, don't forget to change the connection to a production environment and retest before activating.
