= Slack Reference

Use Slack as a data target. For example, you can send a Slack message when a Salesforce opportunity is won.
Some details of how to work with data in a flow are specific to this system, and to the actions you choose.

== Connection Details

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name::

The Slack workspace name, for example, `my-workspace.slack.com`

Username and password::

The username and password that you use to log in to Slack

== Triggers

Use Scheduler to specify when a flow is triggered, for example, every fifteen minutes.

You can't trigger a flow using a connection to Slack.

== Actions

include::_partials/action-definition.adoc[]

Send a direct message to a user::

To post a direct message to a specified user, supply the following information:
+
* *User*: the user to receive the message.
* *Message*: The message to be sent.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name here for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Create a message::

Post a new message to a specific private or public channel that you select.
+
* *Channel Name*: A channel name in the format `#my-channel-name`.
* *Message*: The message to be sent.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Get user by email address::

Find a Slack user by entering their email address into the *Email* field.

[TIP]
If Slack user email addresses aren't in the data returned by your trigger, you can insert this action after the trigger, in order to fetch the Slack user by an email address from another system.
