= NetSuite Reference

Whether you are using NetSuite as a data source (take a new NetSuite contact and copy it to Salesforce for example) or a data target (when
a Salesforce opportunity closes, create a Netsuite sales order), the details of how to work with data in a flow are specific to the data source or data target.

== NetSuite Accounts

Composer requires that you access cloud-based NetSuite accounts, not

== Connection Details

include::_partials/connection-definition.adoc[]

Connection Name::

add details

Account::

add details

Consumer Key::

add details

Consumer Secret::

Token Id::

add details

Token Secret::

add details

== Triggers

include::_partials/trigger-definition.adoc[]

New record::

A new record is created in NetSuite.

Upsert record::

A record is created, or an existing record is updated.

== Actions

include::_partials/action-definition.adoc[]

Search record::

Find and retrieve a record based on search criteria.

Create record::

A record is created.

Update record::

A record is changed.

Upsert record::

A record is created or changed.