= III

Quong Kee's faintly cynical smile didn't make him feel any better. Leaving the place, he glared belligerently at the maniac he had fought with. Marching to the spaceport, his feelings intensified so that he forgot to walk slowly, the first rule on Mars, and had to hold his airpac to his nostrils all the way. By the time he found the Chicago, his fingers were stiff from holding the instrument.

"Damn that living relic of a Quong Kee," he muttered, changing hands. "Damn everything!"

So the girl needed him. He growled at the idea of the Chinese putting the girl ahead of the System News Service.

His sense of humor came through then, and he laughed at himself. Ron Barnard, the hardest hearted reporter in the Solar System, was developing a crush on a girl he hardly knew! He chuckled at his emotions as if they were somebody else's.

"If the boys in the city room ever hear of this," he thought, "they'll laugh me right off Earth. I'll have to become a space-beacon keeper."

He stood for a minute sizing up the Chicago. Odd, he reflected, how the human mind before space travel had pictured space craft as wingless and cigar shaped. This rugged model, of an almost forgotten vintage, was short and stubby and wide winged. It scarcely looked spaceworthy, but the skies were filled with old craft like this one.

He used the key Quong Kee had given him and found the ship deserted. The interior was better. He was pleased to find a three-inch layer of Selene between the hulls. The artificial spider silk, closely woven and specially processed, was as tough as any material in existence and its insulating qualities couldn't be matched.

In the spotless control cabin he found that the instruments were fully modern. The cabin was globular; gyroscopes kept the gravity—if any—under its floor. A glance into other compartments brought a whistle to his lips—the Chicago was crammed with fuel and food. Gail Melvin must have prepared this as a permanent home.

Two tiny sections were the sleeping quarters of Gail and George Melvin. He poked around them until a feeling of guilt made him stop. He sank into a spongy, bolted-down chair, damning his new-found ethics. He'd straighten out a few things when that female showed up.

She didn't seem surprised to see him. She glanced his way casually and started tugging off her heavy coat. A gentlemanly impulse almost had him out of his seat to help her, but he stifled it.

Her nose was red from the mild summer weather of Mars, and he thought briefly that if her cheeks were a little fuller, she would probably be more or less good looking. As a matter of plain fact, she was too damned skinny. She must spend most of her time worrying about her brother.

She was taller than he had thought, but still looked slight and helpless. And hopeless as well. Her shoulders drooped a little as she faced him.

"I saw Quong Kee," she said.

"Oh—I'm sorry about your brother." He hesitated. "Have you any idea who did it?"

He almost squirmed when she looked at him. The expression in her eyes was not entirely friendly.

"I have ideas," she said. "And they're not nice."

Her eyes were dark and smoldering now.

"They questioned George with a new type of lie detector—Skolssolky or some such name. I wasn't supposed to know—"

Barnard's eyebrows went up. "The police questioned George? Somebody must have found out!"

Gail dropped her coat over the back of another chair and sat on the chair. She was pale and her eyes were haggard.

"When I found the police had picked him up," she said, "I took an espine pill and became en rapport with him."

She pressed her slender fingers against her temples. "I'm tired ... espine isn't as bad as neoin, of course, but it has a strong reaction. They found out some things from George that I'd never been able to find out.

"This instrument reaches deeper into the subconscious than anything ever used before. Even so, everything was vague. But George had been on Pluto. Somehow he'd followed the neoin trail there; how, I don't know.

"But on Pluto, they did something to him. They took his mind and made him like a new-born child. His brain was perfectly blank. I've been teaching him as I'd teach an infant—but he was so slow learning."

"Pluto—" Barnard stared. "Then neoin comes from Pluto. Lansfer knows this—"

He looked at the girl and damned his conscience again. There was a first aid box set into the wall, and he found a bottle of brandy in it. A small black bottle was there. He noted the label—Espine, another outlawed drug the authorities tolerated for emergency purposes. Not habit-forming, but continued use of it would soften the brain and wreck the nerve centers.

He slammed the cabinet door on the black bottle. She had reason to be tired.

He made her drink the brandy. She spoke softly, between sips. "When I heard that, I determined to go to Pluto. If something there could take my brother's intelligence away, we might be able to reverse the process."

"Or lose your own," Barnard murmured.

"When Quong Kee told me about the—George, it changed all that, of course. There was no need to go to Pluto."

"You've got your nerve," Barnard growled. "You speak very calmly about invading Pluto single handed."

Definitely, Pluto was no place for her. But he had to be in on the kill. Would Lansfer cooperate?

"Miss Melvin," he said, "I'll have to see the Space Police, find out if they'll take me with them. I suspect they won't. So I'm going to cable my boss for money, and if it's all right with you, I'll charter this ship—"

"I'll be very happy," she said, "to take you with me to Pluto—so you can get your story."

He stared. "But—you mean you still intend to go to Pluto? What possible reason could you have now?"

She reached for her coat and dug into the sleeve. Barnard blinked when three of her fingers came out at the shoulder.

"That hole," she said, "was made by a bullet. Somebody took a shot at me on the way over here, and I've been followed. Evidently they've decided I know too much. I'll never step out that door alive."

She indicated a red pane of glass on the instrument panel. "If that glows, they're approaching the ship. Be ready to give them a warning blast from the rockets."

Barnard thought wistfully of the gun he had left in his hotel room. "That means I'm here for keeps, too. But you can't go to Pluto. I'll drop you off at another Martian city—or on some other planet that's on our route."

"Did you ever operate a space ship?" she asked.

"No, but—"

She shook her head. "Besides, they have agents everywhere. My life isn't worth a counterfeit milliplatin. So I might just as well go to Pluto."

Barnard sprang to life as the detector signal glowed deep red. He leaped to the handles of the rocket jets, prepared to throw out a warning blast.

There was a pounding on the hull. "Open up, in there! It's the Space Police!"

"That's Lansfer's voice." Barnard hesitated at the lock. "That means we're safe—or does it? Is this ship ready to take off?"

"Yes—"

"Then—just on a hunch—get at the control board—"

He closed the inner door of the lock behind him before he opened the outer. No use silhouetting himself against the lighted interior.

Lansfer almost lost his poker face. "You! You'll get into trouble, Barnard, if you're not careful. What are you doing here?"

"Guest of Miss Melvin, commander. And you?"

The officer indicated a paper. Barnard noted that his other hand remained close to his holster.

"We're impounding this ship. The Space Police can't be responsible for old wrecks endangering human life and limb on the spaceways."

"Very thoughtful of the Space Police all of a sudden," said Barnard.

There were two other patrolmen with Lansfer, he saw. Remish and a red-haired man he knew to be named Grady. His searching eyes picked out several shadowy figures lurking at corners of the field. He looked again at Lansfer.

"You have our word," he said, "that this ship is to be used only as living quarters by Miss Melvin."

Lansfer stared coolly up at him. "This court order calls for the Chicago to be delivered immediately into the custody of the sheriff and auctioned for scrap. You and Miss Melvin will leave it immediately."

Barnard nodded agreeably. "All right, commander. We'll leave—right now."

Lansfer relaxed. He was about two feet below Barnard, the platform being that high from the ground. Barnard reached out carefully with his foot and shoved. The spaceman flew backwards into Grady, and the two of them crashed to the frozen ground.

Barnard pulled the door swiftly. Lansfer was clawing for his gun and shouting for Remish to stop them. Remish's gloved fingers fumbled as he drew and the outer door was closed before he fired. Barnard grinned as the bullets bounced off the door. That hull was more than tough enough to handle all the bullets the Space Police could throw at it.

"Get off the ground, Gail," he shouted.

He slammed the inner door of the lock and swayed with the control room globe as the rockets went into action. The ship jumped forward a few feet, balked for a moment. Gail threw a lever that opened the shutters. They saw the three policemen scrambling madly to both sides as the Chicago started roaring down the field.

They blasted away and left the ground, the police still firing after them. Barnard clung to a bolted-down chair as they lurched wildly. Gail pointed the nose up until the ship would have been hanging from its props, if it had any.

"That's all we needed," said Barnard, sourly. "We're both outlaws now—fair game for anybody. Our only hope is to break the dope ring. And Lansfer, if we can."

She looked distastefully at him. "That would make a good story, wouldn't it? Daring reporter defies police; smashes neoin ring. Of course, there might be some opposition."

"Which way is Pluto?" he asked, changing the subject.

"I haven't the faintest idea. Hand me that book—the big one—"
