= IV

Barnard found that space navigation was more complex than he had thought. He watched in grudging admiration as the girl rejected course after course. Finally she looked up at him and frowned.

"We have to go sunward—the sun is almost directly between us and Pluto. We can get there fast, and speed is our best bet to evade the Space Police. But it'll be dangerous."

"I'll take the chance," said Barnard. "But don't be reckless with your own life. How many months will it take?"

"About four days."

He stared suspiciously at her. "It took me fourteen days from Earth to Mars. What's this crate got that the Inner Planets Line hasn't?"

She smiled. "For a great reporter, you don't know much. They could make the Earth-Mars run in a day—but that's where the danger comes in. If a rock gets in their path, they have to be traveling slow enough for the detectors to find it and change the course. That's done automatically, but we haven't powerful enough detectors yet to handle high speeds."

"Oh, a job for the instrument makers?" Barnard was beginning to realize his ignorance.

"You could put it that way. The chance of hitting anything big enough to hurt a space ship is small, of course, but with hundreds of ships in space, there would be a lot of wrecks if they all went as fast as we're going to go!"

They plunged almost directly into the sun, nose forward to cut down the radiant energy. Gail sat in a sea of charts and tables, calling out instructions to Barnard, who was learning to handle the controls. She kept the rockets blazing, and before many hours had passed they could almost see the sun growing in size.

In the growing warmth, the reporter dozed off to a restless, nightmarish sleep. He awoke with a start to find himself soggy with perspiration, his bones aching. Gail, hunched over her figures, looked up and grinned impishly.

"Warm?" she asked. "The cooling units are going full blast. The vision plates are all shuttered, but if you want to look, I've swung dark glass into place."

She gestured to one of the darkened vision plates, and her fingers slid to a button that opened the shutters. Barnard looked and closed his eyes when he saw the monstrous body that was the sun.

"I've seen enough," he assured her. "Where are we?"

"Inside the orbit of Mercury. We'll be closer before we're farther away."

Barnard studied her. At the most dangerous part of their journey, where space was filled with cosmic debris plunging into the sun, she had lost her hunted look and worked with a graceful nonchalance. She seemed actually to be enjoying the whole thing.

The murderous forces of radiant energy pounded at and through the heavily insulated hulls. Barnard mopped his sweat-soaked face and waited for the metal of the space ship to ignite. He stared at the girl and wondered how she could be so happy and poised, though she was as bedraggled as he was. Was her mind gone, too?

He decided so when she told him, much later:

"Congratulations, Mr. Barnard. Right now you and I are closer to the sun than any other human beings ever have been—"

He studied her face.

She stared through the darkened glass into the inferno. "Except," she said thoughtfully, "for a few unfortunate expeditions that fell into it."

Then they were starting to recede. The Chicago was inside the eccentric orbit of Vulcan, and starting to plunge away from the sun. The tremendous velocity they had been building up was far more powerful than the titanic pull of the sun's gravitational field. Gradually, the temperature went down to a cool 100 degrees, and the two humans, limp and worn, took turns catnapping.

Barnard lugged can after can of fuel for the tanks. The motors pounded constantly, building up greater and greater velocity. At timed intervals, Gail took sights of the visible planets to check their speed.

Their course curved far above the plane of the ecliptic. No passage through the asteroid belt at this speed!

That was Gail's main worry. "We're veering out of the crowded belt, but there're stray asteroids far from the ecliptic plane. If we pass that region, we'll be in fairly empty space, and more or less safe, except for the Space Police."

Barnard raised his eyebrows. "Space Police? How could they trace us at this speed?"

"We're as obvious as a green spaced Venusian in New York," she told him. "It's the speed—we're actually tearing up space. Lansfer's instruments could pick us out from a hundred million miles. But that's a lot of room." She glanced slyly at him. "Now you can write science articles for the Sunday supplements."

"Lay off me," he begged. His questing fingers found a cigarette as the clock ticked over to the hour. Smokes were rationed in space. He lit up and drew smoke into his hungry lungs, then passed the cigarette to Gail.

"At least," he said, "I have a job to do on Pluto, which is more than you can say. What are you going there for?"

She passed the cigarette back.

"It seemed like a good idea at the time," she said.

Barnard stared silently at her. She looked strangely happy, plunging toward God-knew-what evils on far Pluto! He felt suddenly disgusted with the whole affair. They were two fools, defying the Space Police for the right to seek certain death.

"Gail," he said, "don't go through with it. Slow the ship down and get off at the nearest human settlement—one of the Jovian moons, or Titan. I can handle this ship now. My syndicate will pay—"

The entire universe exploded then. He pounded brutally into the concave walls, whirling end over end as the ship spun madly out of control. His head crashed as the spherical control room escaped its gyroscopes and he fought desperately against crushing blackness. Gail—was she mangled, killed? There was a senseless spinning, and then it was dark ... dark....

He fought his way out of the blackness. Something was searing his throat ... he coughed in agony and the shock brought him partly to his senses.

Gail was pouring brandy into him. He saw her by the hard glare of the battery-run light. She was bruised and her coveralls were torn, but she was alive.

He came to his feet and gripped her arms. "Gail?"

Then he stopped. Her eyes were pained and misting. She swayed and collapsed in his arms.

For a moment he was frantic. What to do? He carried her to her room, made her comfortable. Fervently, he hoped no bones were broken. But after a few minutes she opened her eyes and made a face at him.

"I'm not hurt," she said dreamily. "Just a sissy. Go and see what happened."

Gratefully, he watched her relax. He rubbed his hands thoughtfully and studied the damage in the control room. The meteor couldn't have hit very hard—they would have been killed without knowing it. A mere graze!

He reached out fearfully and cut off the blazing rockets. The vision plates were blackened—no way of knowing which way they were going.

That was his first job, then—to unshutter the vision plates. He reviewed his knowledge of the mechanism. Evidently the master switch that controlled them all had been short-circuited. The switch was in the very tail of the ship. He crawled through the hold and into the tiny compartment in the tail.

His pocket flash picked out the switch, and he made with the screw driver. A few seconds later he looked proudly through the opened plate, feeling like a master mechanic.

But he didn't feel so happy when he saw a swifter-moving point of light in the star-filled sky.

A spaceship was closing in on the Chicago. And goose pimples rose on his arms when he recognized it as the police ship of Commander Lansfer.

He had to get back to the control room.

The police ship was coming in at a half mile a second, relative to them. What both ships were doing relative to the system he didn't know, or care. On his hands and knees in the close cubby, he scrambled around to get back to the control room. But already it was too late.

Invisible beams of magnetic force leaped into life between the two vessels, as the law ship clamped down with its Duvals. Barnard was pitched heavily forward as the beams seized the Chicago. His head crashed into something hard, and he fell into a relaxed bundle.
