= V

It was cold, and he was beating his way out of a frozen death. He fought his way up from the floor, a sluggish chill in the marrow of his bones. Frigid ... and he was sinking back.

Remembrance shocked him into wakefulness. He stared from the port before his face. The police ship was there, clamped by invisible forces to the Chicago. Dully, he watched the fore rockets blasting for deceleration.

Deceleration—?

That brought him to frantic life. Were they nearing Pluto? How long had he been out? And—why was it so cold?

His teeth and knees still chattering, he wriggled down the narrow passage, pushed his light before him into the room where he had left Gail. He stared wildly.

She was gone.

Then the police had come aboard while he was unconscious and taken her aboard their vessel.

Back in the control room, he stood helplessly for a few seconds, his mind starting to black out again. No power—the ship was leaking its heat into space. His numbed fingers found the right switches. Heat started to seep into the room, and life seemed to flow back into his body.

But Gail—what of her? His distrust of the solemn-faced Lansfer became suddenly more intense. He had to find out—and he was separated from the police ship by fifty feet that might as well have been miles.

There was another way. He fumbled in the medicine kit, snatched the black bottle labeled "Espine." He'd take a pill, even if it killed him in his weakened condition, and use ESP to find out what went on aboard the other vessel. He tore the stopper from the container and turned it upside down over his palm.

Nothing came out.

He cursed the empty bottle fervently, because already the only other answer was coming to his mind. He almost tried not to think of it. But this was emergency.

In one of his pockets he found the tiny packages of neoin he had bought while cultivating the peddlers on Mars.

There was a tiny pinch of gray powder in the paper he tore open. One gram—a normal dose. Full strength, he was sure—the stuff was seldom cut.

He hesitated. Even one dose of the drug created a craving for more. He vowed grimly that this first taste would be his last.

But this made his fight personal. He must destroy the source of neoin in sheer self-defense!

Before the gray powder was past his tonsils, he knew he had taken too much for a beginner. A fantastic lift, a great self-confidence almost sent his mind out of the world. Grimly he fought to keep down the giddy exhilaration, and let his thoughts search for Lansfer's ship.

He had trouble coordinating his thoughts, because of the tendency of his drugged mind to stray. But he caught the control room of the police ship.

Carefully, he kept away from the minds of the four people there. There was an added lift when he perceived Gail, small and defiant, facing Commander Lansfer.

It was Barnard's first experience in extra-sensory perception. With all the power of his will, he focussed his thoughts on the scene. Gail was speaking.

"I tell you," she said, "the reporter is on Earth. He said something about having a big lead. I took the ship into Earth's atmosphere and he bailed out in a parachute. I was glad to be rid of him."

Barnard hoped that what she said was entirely untrue.

"You say—" Lansfer's face was without expression—"that he forced you to do this?"

"I said no such thing," Gail told him. "And if you're going to twist my statements, I'll say nothing more."

Lansfer's palm flicked out and Gail's head reeled. A vivid patch of red appeared on her cheek. Barnard's fingers tightened around the spongy arms of his chair.

The commander turned swiftly to Remish and Grady. None of the officers noticed—but Barnard did—that Gail's fingers were sliding along the control board.

"Barnard is aboard that ship," Lansfer snapped. "You two couldn't have searched very thoroughly. This girl is lying—she couldn't possibly have slowed down enough to let Barnard 'chute to Earth, and still have come this far."

Remish looked uncertain. "Commander—you're the boss here, but—"

"But what?" Lansfer barked.

Remish's eyes darted briefly to where the red welts stood out on Gail's cheek. He licked his lips and for a second his gaze met Grady's. For a moment he hesitated, then faced Lansfer again. He shrugged briefly.

"Never mind," he said. "We'll talk it over at headquarters later."

Lansfer lost some of his poise. He glared at the two patrolmen. "You two get back to the Chicago. Find Barnard and bring him to me!"

Barnard saw Gail's hand hovering over the tiny bar. Suddenly he was shocked. He realized that the bar controlled the Duvals—the magnetic beams that pinned the two ships together. Then she had felt his presence and was waiting for a signal from him. He shouted the thought:

"No!"

Swiftly she disobeyed him, and twisted the bar. In almost the same instant she snatched the gun from Lansfer's holster. She backed away a step and leveled it at the officer.

"Turn this ship around," she ordered. "We're going back to Mars."

Lansfer's narrowed eyes peered at the control board where she had disconnected the grapples. He turned to the girl. His voice was flat, sullen.

"Give me that gun."

"No." She backed away another step and he followed, hand reaching. Her face became paler. Lansfer stopped and stared into her eyes. His eyes were compelling, hypnotic. She stood motionless and tried to shake the effect. Lansfer moved a step closer.

Remish's hand gently removed the gun from her fingers.

Barnard swore disgustedly. Why had Gail cut the grapples? She must have some fool idea that he could beat the police to Pluto, win out on his own.

Maybe he could. There were only two little difficulties involved. First, he didn't know where Pluto was, or how to find it. Second—the planet was Earth-size, and where on its millions of square miles of surface was whatever he wanted?

The second problem was partly solved. From Lansfer's mind he had a vague picture of a vast white sea, trapped in a ring of white mountains that knifed into a black sky.

From Lansfer's mind—!

Even in his neoin jag, a jolt came to him. How did Lansfer know that? Frantically, his thoughts speared back to the police ship. But it was too far now—only confused fragments came.

But one image brought him to his feet, sobered and fearful for Gail's safety. Wildly he searched space for the magenta blasts of the police ship's rockets.

Because his extra-sensory perception brought one clear image. In Lansfer's pocket he had perceived the ancient twentieth century coin he had given to George Melvin.
