= Release Notes for MuleSoft Composer for Salesforce - 2024

Use MuleSoft Composer for Salesforce to build connected experiences faster. You don't need to wait for development resources to unlock data, integrate apps, and automate business processes that create real customer value.

New versions are automatically available once they are released; you don't need to perform any tasks to move to the new version.

See xref:ms_composer_release_notes_ki.adoc[Known Issues and Limitations for MuleSoft Composer for Salesforce] for a list of known issues and limitations by date.

== March 21, 2024

include::_partials/release-notes/rn-headings.adoc[tag=whatsNew,leveloffset=+3]

* You can now view descriptions of connector actions and triggers directly under their respective names.  

== March 15, 2024

include::_partials/release-notes/rn-headings.adoc[tag=fixedIssues,leveloffset=+3]

[%header%autowidth.spread]
|===
|Issue Resolution |ID
|After an access token expires, Salesforce Marketing Cloud Connector now properly refreshes the access token.| W-14979479
|===

== January 9, 2024

include::_partials/release-notes/rn-headings.adoc[tag=whatsNew,leveloffset=+3]

* For triggers in the following connectors, the *Polling Frequency* field is now required: 

** Microsoft Dynamics 365 Business Central  
** Workday 
** Xero
+ 
This field enables you to select how often Composer makes a request to the underling system API to look for changes to records in active flows.
