= Field Mapping

You can manipulate data in Composer by building expressions and applying functions. With the *Custom Expression* editor, you can use DataWeave functions for number, string, or date manipulation using simple math, truncating, capitalizing or setting a date.

== Prerequisites

* Each underlying dataweave function will have a user-friendly name (if deemed necessary), which is how it will be labeled to the end user.
* Each function will have a one sentence explanation about how it performs and to which data type(s) it can be applied.
* The functions that accept data types (as input) other than the data type of the output field will not be displayed.
* Only data pills of the same data type as the field will be shown (other than for string fields where automatic type casting is already supported).
* Functions can be nested. I.e. the input parameters of a function can be another function call. f(f(datapill))

Conditionals:
The data pills and formulas displayed in the if/else block for the value are dependent on the data type of the field selected.

== DataWeave Functions

=== Math

The following formulas and operators and supported: +, -, *, /, ( ), ^

Additionally,


For fields of type number in action cards, we will support a different editor in the “advanced” mode. The editor will support data pills of data type number, numbers (manual input), and the following operators:
+, -, *, /
It will also support parenthesis which dictate the order of operations
It will not support data pills of data type other than number or inputs other than numbers or the above operators
Note: These are the same dataweave operators and operators used in Salesforce function editor and in Workato
The other types of functions cannot be selected in this mode (until the future state when we support typecasting)

=== Dates

The following formulas and operations are supported:

* Basic Dates
** Today
** Now

* Date Calculations
** Days between
** Add days (specify how many)
** Add years (specify how many)
** Add hours (specify how many)
** Add minutes (specify how many)
** Add seconds (specify how many)

* Beginning/end of time period
** Beginning of the hour
** Beginning of the day
** Beginning of the week
** Beginning of the month
** Beginning of the year

The underlying system (connector) should re-format the date to the format that the end system requires. The user is not required to provide the expected format. We will not surface a specific function to handle this case.

=== Strings

[%header%autowidth.spread]

|===

|Composer Formula |DataWave Formula |Formula Definition

|today |Dates::today |Returns current date.
|now |now | Returns current date and time.
|addDays(#), addMonths(#), addYears(#) | Periods::days(#),

|===

=== Numbers

The following formulas and operations are supported:

* Round
* Ceil
* Floor
* Abs



=== Null Values


== Adding a Formula

.

== Configuring a Formula
