= Google Sheets Connector Reference

Use Google Sheets as a data source (get a new Google Sheet row and send a Slack message with information from the row, for example)
or a data target (get a new Salesforce contact and turn it into a row in a Google Sheet).
Some details of how to work with data in a flow are specific to the data source or data target, and also change depending on the specific trigger or actions you choose.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
Composer launches an authentication dialog where you choose which Google Drive account you're connecting to Composer, and if you aren't already logged in, you enter a username and password.

== Triggers

include::_partials/trigger-definition.adoc[]

New spreadsheet::

This trigger fires when a new spreadsheet is created in the Google Drive associated with the connection.
+
Google Sheets are not saved at the moment of creation. They are saved the first time they are edited. Therefore, a new spreadsheet won't trigger a flow until after it is edited and saved. However, the save date is the time of creation, not the first edit. Thus, if you create a second spreadsheet and edit it before you edit the first one, the second spreadsheet triggers a flow; the first one is ignored.

New row in sheet::

Monitors one sheet within a spreadsheet and triggers when a new row is added at the end of the sheet. When a flow is initiated, this trigger returns up all existing rows in the sheet. Each subsequent time that the flow is triggered, new rows added to the sheet are returned.
+
Once text is present in one cell or column, updating those cells or columns does not trigger as a new row. To trigger a new row when updating a cell or column, use the *Update row in sheet* trigger.

Updated row in sheet::

Monitors one sheet within a spreadsheet and triggers when a row is created or updated. When a flow is initiated, this trigger returns all existing rows in the sheet. Each subsequent time that the flow is trigged, new or updated rows in the sheet are returned.

New spreadsheet::

This trigger fires when a new spreadsheet is created in the Google Drive associated with the connection.
+
Google Sheets are not saved at the moment of creation; instead, they are saved the first time they are edited. Adding a new spreadsheet won’t trigger a flow until after that spreadsheet is edited and saved. The date on which the spreadsheet is saved is the date of creation. If you create a second spreadsheet and edit it before you edit the initial spreadsheet, the second spreadsheet triggers a flow and the first spreadsheet is ignored.

=== Limits

* Sheets limited to 10,000 rows
* Header rows excluded
* Trigger works with My Drive, not Team Drive

== Actions

include::_partials/action-definition.adoc[]

Create row::

This action adds a new row at the end of the sheet named in the connection.

Update row::

This action updates a row in a sheet.

=== Limits

* A Google Sheet must have a header row. If data is stored in row #1, the action fails.
* Google Sheets does not write to a cell if the composite data pill has a null or empty value. This could affect the *Update row* or *Create row* actions.

*Google Sheets™ is a trademark of Google LLC.*

include::_partials/see-also.adoc[]
