= Build Formulas for a Flow

You can manipulate data in Composer by building expressions and applying functions. With the *Custom Expression* editor, you can use DataWeave functions for number, string, or date manipulation using simple math, truncating, capitalizing or setting a date.

== Before You Begin

* Only functions that accept data types as inputs appear.
* Only data pills of the same data type as the field appear. This does not apply to string fields where automatic type casting is already supported.
* Functions can be nested. The input parameters of a function can be another function call.
* The data pills and formulas displayed in the if/else block for the value are dependent on the data type of the selected field.

== DataWeave Functions

Composer uses https://docs.mulesoft.com/dataweave/2.3/dw-operators[DataWeave] operators to build custom expressions.

=== Math Functions

The following formulas and operators and supported: `+, -, *, /, ( ), ^`

Additionally:

* Only data pills of the type `number` are supported.
* For fields of the type `number` in actions, Composer provides an advanced editor that supports data pills of data type `number`, ~ (manual input), and the following operators: `+, -, *, /`
* Parentheses dictate the order of operations.


=== Date Functions

The following formulas and operations are supported:

* Basic Dates
** Today
** Now

* Date Calculations
** Days between
** Add days (specify how many)
** Add years (specify how many)
** Add hours (specify how many)
** Add minutes (specify how many)
** Add seconds (specify how many)

* Beginning/end of time period
** Beginning of the hour
** Beginning of the day
** Beginning of the week
** Beginning of the month
** Beginning of the year


=== String Functions

[%header%autowidth.spread]

|===

|Composer Formula |DataWave Formula |Description

|today |Dates::today |Returns current date.
|now |now | Returns current date and time.
|addDays(#)
|addMonths(#)
|addYears(#)| Periods::days(#),

|===

=== Number Functions

The following formulas and operations are supported:

* Round
* Ceil
* Floor
* Abs



=== Null Values


== Adding a Formula

.

== Configuring a Formula
