= Build Formulas for a Flow

You can manipulate data in Composer by building expressions and applying functions. With the *Custom Expression Editor*, you can create expressions that include functions and mathematical operators. For example, you can truncate words, capitalize phrases, and set the date.

== Before You Begin

//More content may be added - to be determined later
* Functions can be nested. The input parameters of a function can be another function call.
* The functions used in Composer are built using https://docs.mulesoft.com/dataweave/2.3/dw-operators[DataWeave].

== About the Custom Expression Editor

Using the Custom Expression Editor, you can manipulate your input data by building expressions and applying functions beyond a basic one-to-one mapping.

=== String Functions

The Custom Expression Editor supports the following `string` formulas and operators:

[%header%autowidth.spread]
|===

|Function Name |Description |Example |Input Data Type Parameters |Output Data Type

|lower | Returns the provided string in lowercase characters. |`lower(COMPOSER) = composer` |text: String |String

|upper |Returns the provided string in uppercase characters. |`upper(composer) = COMPOSER` |text: String |String

|capitalize |Capitalizes the first letter of each word in a string. This also removes underscores between words and puts a space before each capitalized word.
|`capitalize(name) = Name` +

`capitalize(firstName) = First Name` +

`capitalize(customer_first_name) = Customer First Name` +
|text: String |String

|trim |Removes any blank spaces from the beginning and end of a string.
|`trim(<long example text>) = this example long text` |text: String |String

|first |Returns the specified number of characters from the beginning  characters from the beginning of a string. For example, the first five characters of a string.
If the number is equal to or greater than the number of characters in the string, the function returns the entire string. |`first(Hello Composer!, 5) = Hello` |text: String +

numCharacters: Number |String

|last |Returns the specified number of characters from the end of a string.  For example, the last nine characters of a string. |`last(Hello Composer!, 9) = Composer!` |text: String +

numCharacters: Number|String

|substitute |Replaces all substrings that match a literal search string with a specified replacement string. Replacement proceeds from the beginning of the string to the end. For example, the result of replacing `aa` with `b` in the string `aaa` is `ba`, rather than `ab`. |`substitute(Composer, o, O) = COmpOser` +

`substitute(Composer, a, Example) = Composer`

|text: String +

target: String +

replacement: String |String

|===

=== Number Functions

The Custom Expression Editor supports the following `number` formulas and operators:

[%header%autowidth.spread]
|===

|Function Name |Description |Example |Input Data Type Parameters |Output Data Type

round
Rounds a number up or down to the nearest whole number.
round(1.2) = 1
round(4.6) = 5
round(3.5) = 4
number: Number
Number
ceil
Rounds a number up to the nearest whole number.
ceil(1.2) = 2
ceil(3) = 3
number: Number
Number
floor
Rounds a number down to the nearest whole number.
floor(2.2) = 2
floor(3) = 3
number: Number
Number
abs
Returns the absolute value of a number.
abs(-3.4) = 3.4
abs(2) = 2
number: Number
Number


|  |  |  |  |
|  |  |  |  |
|  |  |  |  |

|===

=== Date Functions

Formulas that are duplicated for `Date` and `DateTime` (e.g. `addDays`, `beginningOfMonth`, etc) are appended with `_Date` and `_DateTime`.

The Custom Expression Editor supports the following `date` formulas and operators:

[%header%autowidth.spread]
|===

|Function Name |Description |Example |Input Data Type Parameters |Output Data Type

|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
today
Returns the date for today as a Date type.
today() = 2021-03-15


Date
now
Returns a DateTime value for the current date and time.
now() = 2021-03-15T18:23:20


DateTime
addDays
Creates and returns a Date value incremented or decremented by the specified number of days
addDays(today(), 3) = 2021-03-18

addDays(2021-03-15, -4) = 2021-03-11
date: Date
numDays: number
Date
addDays
Creates and returns a DateTime value incremented or decremented by the specified number of days
addDays(now(), 3) = 2021-03-18T18:23:20

addDays(2021-03-15T18:23:20, 3) = 2021-03-18T18:23:20
dateTime: DateTime
numDays: number
DateTime
addMonths
Creates and returns a Date value incremented or decremented by the specified number of months.
addMonths(today(), 3) = 2021-06-15

addMonths(2021-03-15, -4) = 2020-12-15
date: Date
numMonths: number
Date
addMonths
Creates and returns a DateTime value incremented or decremented by the specified number of months.
addMonths(now(), 3) = 2021-06-15T18:23:20

addMonths(2021-03-15T18:23:20, -4) = 2020-12-15T18:23:20
dateTime: DateTime
numMonths: number
DateTime
addYears
Creates and returns a Date value incremented or decremented by the specified number of years.
addYears(today(), 1) = 2022-03-15

addYears(2021-03-15, -1) = 2020-03-15
date: Date
numYears: number
Date
addYears
Creates and returns a DateTime value incremented or decremented by the specified number of years.
addYears(now(), 3) = 2024-03-15T18:23:20

addYears(2021-03-15T18:23:20, -1) = 2020-03-15T18:23:20
dateTime: DateTime
numYears: number
DateTime
addHours
Creates and returns a DateTime value incremented or decremented by the specified number of hours.
addHours(now(), 1) = 2021-03-15T23:23:20

addHours(2021-03-15T22:23:20, 3) = 2021-03-16T01:23:20

addHours(2021-03-15T22:23:20, -4) = 2021-03-15T18:23:20
dateTime: DateTime
numHours: number
DateTime
addMinutes
Creates and returns a DateTime value incremented or decremented by the specified number of minutes.
addMinutes(now(), 5) = 2021-03-15T18:33:20

addMinutes(2021-03-15T23:45:00,15) = 2021-03-16T00:00:00

addMinutes(2021-03-15T18:23:20, -30) = 2021-03-15T17:53:20
dateTime: DateTime
numMinutes: number
DateTime

addSeconds
Creates and returns a DateTime value incremented or decremented by the specified number of seconds.
addSeconds(now(), 30) = 2021-03-15T18:23:50

addSeconds(2021-03-15T23:45:00,15) = 2021-03-15T23:45:30

addSeconds(2021-03-15T18:23:20, -30) = 2021-03-15T18:22:50
dateTime: DateTime
numSeconds: number
DateTime
beginningOfHour
Returns a new DateTime value that changes the Time value in the input to the beginning of the specified hour.

The minutes and seconds in the input change to 00:00.
beginningOfHour(2021-03-15T18:23:20) = 2021-03-15T18:00:00
dateTime: DateTime
DateTime
beginningOfDay
Returns a new DateTime value that changes the Time value in the input to the beginning of the specified day.
The hours, minutes, and seconds in the input change to 00:00:00.
beginningOfDay(2021-03-15T18:23:20) = 2021-03-15T00:00:00
dateTime: DateTime
DateTime

beginningOfWeek
Returns a new Date value that changes the Day value from the input to the beginning of the first day of the specified week.
The function treats Sunday as the first day of the week.
beginningOfWeek(2021-03-15) = 2021-03-14

beginningOfWeek(today()) = 2021-03-14


date: Date
Date
beginningOfWeek
Returns a new DateTime value that changes the Day and Time values from the input to the beginning of the first day of the specified week.
The function treats Sunday as the first day of the week.
beginningOfWeek(2021-03-15T18:23:20) = 2021-03-14T00:00:00

beginningOfWeek(now()) = 2021-03-14T00:00:00


dateTime: DateTime
DateTime
beginningOfMonth
Returns a new Date value that changes the Day value from the input to the first day of the specified month.
beginningOfMonth(2021-11-15) = 2021-11-01

beginningOfMonth(today()) = 2021-03-01
date: Date
Date
beginningOfMonth
Returns a new DateTime value that changes the Day value from the input to the first day of the specified month.
The day and time in the input changes to 01T00:00:00.


beginningOfMonth(2021-03-15T18:23:20) = 2021-03-01T00:00:00

beginningOfMonth(now()) = 2021-03-01T00:00:00
dateTime:
DateTime
DateTime

beginningOfYear
Returns a new Date value that changes the Month and Day values from the input to the first day of the specified year.
beginningOfYear(2021-11-15) = 2021-01-01

beginningOfYear(today()) = 2021-01-01
date: Date
Date
beginningOfYear
Returns a new DateTime value that changes the Month and Day values from the input to the first day of the specified year. It also sets the Time value to 00:00:00.
The month, day, and time in the input changes to 01-01T00:00:00.
beginningOfYear(2021-03-15T18:23:20) = 2021-01-01T00:00:00

beginningOfYear(now()) = 2021-01-01T00:00:00
dateTime: DateTime
DateTime
daysBetween



Returns the Number of days between two Dates.

If the to Date is earlier than the from Date, the function returns a negative number equal to the number of days between the two Dates.
daysBetween(2020-03-15, 2021-03-15) = 365
from: Date
to: Date
Number
daysBetween


Returns the Number of days between two DateTimes.

If the to DateTime is earlier than the from DateTime, the function returns a negative number equal to the number of days between the two DateTimes.
daysBetween(2020-03-15T18:23:20, 2021-03-15T02:23:20) = 365
from: DateTime
to: DateTime
Number

month


Returns the numerical value of the month in the Date input.
month(2021-03-15) = 3
date: Date
Number
month


Returns the numerical value of the month in the DateTime input.
month(2021-03-15T18:23:20) = 3
dateTime: DateTime
Number
year


Returns the numerical value of the year in the Date input.
year(2021-03-15) = 2021
date: Date
Number
year


Returns the numerical value of the year in the DateTime input.
year(2021-03-15T18:23:20) = 2021
dateTime: DateTime
Number


|===


== Related Resources

ifeval::["{product}"=="salesforce"]
* xref:ms_composer_overview.adoc[Mulesoft Composer for Salesforce: Overview]
endif::[]

ifeval::["{product}"=="mulesoft"]
* xref:ms_composer_overview.adoc[Mulesoft Composer: Overview]
endif::[]

ifeval::["{product}"=="salesforce"]
* xref:ms_composer_prerequisites.adoc[MuleSoft Composer for Salesforce: Getting Started]
endif::[]

ifeval::["{product}"=="mulesoft"]
* xref:ms_composer_prerequisites.adoc[MuleSoft Composer: Getting Started]
endif::[]

* xref:ms_composer_flows.adoc[Build and Test a Flow]
* xref:ms_composer_activation.adoc[Activate a Flow]
* xref:ms_composer_monitoring.adoc[Monitor a Flow]

ifeval::["{product}"=="salesforce"]
* https://help.salesforce.com/s/search-result?language=en_US&f%3A%40sflanguage=%5Bes%5D&sort=relevancy&f%3A%40sfkbdccategoryexpanded=%5BAll%5D&t=allResultsTab#t=allResultsTab&sort=date%20descending&f:@objecttype=%5BKBKnowledgeArticle%5D&f:@sflanguage=%5Ben_US%5D&f:@sfkbdccategoryexpanded=%5BAll,MuleSoft%20Composer%5D[Knowledge Articles]
endif::[]

ifeval::["{product}"=="mulesoft"]
* https://help.mulesoft.com/s/global-search/%40uri#t=SalesforceArticle&f:@sfdcproduct=%5BMuleSoft%20Composer%5D[Knowledge Articles]
endif::[]
