= Preparation Checklist for Composer

Before you build a flow, assemble the information you need:

* The username, password, and the URL where you send these credentials for every data source or data target.
This user must have access to the data you plan to work with. +

* The trigger for your flow: an event like "a Google Sheet row is updated when I add a new Salesforce contact,"
or a time period like "every fifteen minutes."

* An ordered list of all the steps and all the logic required to move and transform your data:

    ** Which records, rows, or other data do you need to access?
    ** What are you trying to do? For example:
        *** Pull changes and copy them
        *** Transform the structure or type of the data
        *** Add information from one source to information in another
    ** Will you filter out some records based on criteria such as "owned by," or "updated after"?

Of course, if you aren't certain of some of this information, you can still use Composer.
Flows, the main building block of process automation, don't start working until you activate them.
You can change them as you create them, so feel free to experiment.

include::_partials/see-also.adoc[]
