= ServiceNow Connector Reference

ServiceNow is an IT Service Management (ITSM) system that helps IT organizations manage service requests and incidents reported by employees as well as service requests from partners, vendors, and customers.

[NOTE]
====
To view sample data in ServiceNow Connector, you can either:

* Go to ServiceNow and then go to *System Properties* > *Web Services*. Select the *Yes* checkbox under the `This property sets the elementFormDefault attribute of the embedded XML schema to the value of unqualified, if set to true. This attribute indicates whether or not locally declared elements must be qualified by the target namespace in an instance document. If the value of this attribute is 'unqualified', then locally declared elements should not be qualified by the target namespace. If the value of this attribute is 'qualified', then locally declared elements must be qualified by the target namespace. For compatibility with Clients generated from WSDL (.NET Web Reference, Axis2 stub, webMethods, ect.), set this value to false. This value defaults to true.`. Click *Save*.
* Go to ServiceNow and in the navigation filter, enter `sys_properties.list`. Find the `glide.wsdl.schema.UnqualifiedElementFormDefault` property and set it to `true`.
====

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Only users with the ServiceNow `soap_admin` role can create connections. For more information, see the ServiceNow help: https://community.servicenow.com/community?id=community_question&sys_id=86da8b6ddb5cdbc01dcaf3231f961958

Instance URL::

The URL or ID of your ServiceNow instance.

Username::

The username that you use to log in to ServiceNow.

Password::

The password that you use to log in to ServiceNow.


== Triggers

include::_partials/trigger-definition.adoc[]

New or Updated Record::

Checks for new or updated records in the ServiceNow `record_type` table. Provide a value for *Table name*.
+
Note that *ServiceNow Time Zone* must be set to the same time zone as your ServiceNow instance.

NOTE: To view custom or extended parent tables in ServiceNow Connector, select the *Allow access to this table via web services* and *Allow configuration* options in the table definition.

=== Polling Frequency 

include::_partials/polling-frequency.adoc[]

== Actions

include::_partials/action-definition.adoc[]

Search Record::

Searches for an existing record using a query string that specifies record type criteria. Provide a value for the following fields:
* *Table name*
* *Query*
+
If the value in the *Table name* field is `sysparm_no_count`, then this value is set to `True` by default. For more information, see the ServiceNow documentation: https://developer.servicenow.com/dev.do#!/reference/api/orlando/rest/c_TableAPI#r_TableAPI-GET.

Create Record::

Creates a new entry of the selected record type table in ServiceNow. Provide a value for *Table name*.

Update Record::

Updates an existing entry of the selected record type table in ServiceNow. Provide a value in the following fields:
* *Table name*
* *Sys ID*

NOTE: To view custom or extended parent tables in ServiceNow Connector, select the *Allow access to this table via web services* and *Allow configuration* options in the table definition.

== Custom Fields 

Custom fields are not supported. Using MuleSoft Composer, you can access standard field values for actions and triggers that you set in the ServiceNow record.

include::_partials/see-also.adoc[]
