= Automation Credits Usage and Rates

Your MuleSoft Automation subscription plan includes a quota of Automation Credits that depletes as you create and execute automations.

Credit usage rates differ for different subscription plans. Refer to the article that corresponds to your subscription plan as shown in the following table: 

[%header%autowidth.spread,cols="a,a]
|===
| Subscription Plan | Conversion Rate Sheet
a| 
* Automation Starter
* Automation Advanced 
* Automation for vCore/Core
* Additional Automation Credits
.^| xref:ms_composer_automation_credits_2.adoc[MuleSoft Automation Credits 2.0]
a|
* MuleSoft - Automation
* MuleSoft - Automation - (Gold, Platinum, Titanium Edition)
* MuleSoft - Automation for Salesforce
* MuleSoft - Automation for Salesforce - (Gold, Platinum, Titanium Edition)
* MuleSoft - Automation - Additional Credits (100)
* MuleSoft - Automation - Additional Credits (100) - (Gold, Platinum, Titanium)
.^| xref:ms_composer_automation_credits.adoc[MuleSoft Automation Credits 1.0]
|===

For more information on usage and pricing metrics, see xref:general::pricing-metrics.adoc#metrics-collected-in-anypoint-platform[Metrics Collected in Anypoint Platform].

== Monthly Account Summary Emails

Salesforce sends usage-based billing reports to every MuleSoft Composer customer on the 10th of each month. By default, Salesforce sends these emails to the account's billing contact. 

For additional information about the reports, the list of recipients, and other details, see the https://help.salesforce.com/s/articleView?id=000390885&type=1[Monthly Account Summary Email FAQ^].  

include::_partials/see-also.adoc[]