= Jira Connector Reference

Jira is a powerful project management tool and ticketing system used to help users plan, track, release, and report product issues in order to improve development.

To use Jira Connector with Composer, you must have the _Administrator Jira_ global permission. For more information, see the https://support.atlassian.com/jira-work-management/docs/manage-permissions/[Jira documentation^].

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

OPTIONAL: Organization Site URL::

Enter the URL of the Jira organization containing the sandbox or production environment to which you want to connect. If you do not specify a value in the *Organization Site URL* field, the connection uses the first URL listed in the `/resources` endpoint of the Atlassian API. For more information about Jira organizations, see the https://support.atlassian.com/organization-administration/docs/get-started-with-an-atlassian-organization/[Jira documentation^]. 
+
To connect to a Jira organization via an Atlassian account: 

. In the *Connect to your Jira Account* window, in the *Organization Site URL* field, enter the Jira organization URL. For example, `+https://orgname.atlassian.net+`.  
. Click *Connect*. +
An Atlassian window appears, indicating that Composer is requesting access to an Atlassian account. 
. In the window, in the *Authorize for site* dropdown, select the organization you want to use and then click *Accept*. +
Composer is now connected to your Jira organization.  

Username::

The OAuth username that you use to log in to Jira.

Password::

The OAuth password that you use to log in to Jira.

== Triggers

include::_partials/trigger-definition.adoc[]

New issue with Custom Fields::

Checks for a new issue with Custom fields created in Jira.

New issue with Standard Fields only::

Checks for a new issue with Standard fields created in Jira.

Update issue with Custom Fields was updated or created::

Checks for updated or created issues with Custom fields in Jira.

Update issue with Standard Fields only was updated or created::

Checks for updated or created issues with Standard fields in Jira.

== Actions

include::_partials/action-definition.adoc[]

Create issue with custom fields::

Creates a new issue within the selected project. Provide a value for the following fields:

* *Project*
* *Key*
* *Summary*
* *Type*
* *Status*
* *Priority*

Update issue with custom fields::

Updates specified Custom field values. Provide a value for the following fields:

* *Issue ID or Key*
* *Notify Users*

Update issue with standard fields only::

Updates specified Standard field values. Provide a value for the following fields:

* *Issue ID or Key*
* *Notify Users*

Assign user to issue::

Assigns a user to a specified issue. Provide a value for *Issue ID or Key*.

Add watcher to issue::

Adds a watcher to an existing Jira issue. Provide a value for *Issue ID or Key*.

Get issue::

Returns details for a specific issue. Provide a value for *Issue ID or Key*.

Add comment to issue::

Creates and adds a comment to an existing issue. Provide a value for the following fields:
* *Issue ID or Key*
* *Comment Text*

Get account IDs for users::

Returns the account IDs for the users specified in the `key` or `username` parameters. You can specify multiple `key` or `username` parameters.

Create project::

Creates a new project based on a project type template in Jira. Provide a value for the following fields:

* *Key*
* *Name*
* *Lead Account ID*
* *Project Type Key*: The value in this field must begin with an uppercase letter followed by one or more uppercase letters or numbers.

Get project::

Returns the project details in Jira. Provide a value for *Project ID* or *Key*.

Update project::

Updates the project details for an existing project in Jira. Provide a value for *Project ID* or *Key*.

Retrieve attachments for an issue::

Returns all attachments for this issue. This returns the files' metadata but not the contents of the files. The files are ordered by the date that they were uploaded. Provide a value for *Project ID* or *Key*.

Retrieve attachment::

Returns a URL redirect to the raw file for a specified file attachment. Provide a value for *Attachment ID*.

Upload attachment to an issue::

Uploads attachment to a Jira issue. Provide a value for the following fields:

* *Issue ID or Key*
* *File Name*

== Custom Fields

Using MuleSoft Composer, you can access Standard  custom field values in Jira for actions and triggers that you set in the Jira issue.

include::_partials/see-also.adoc[]
