= MuleSoft Automation Credits 2.0

Your MuleSoft Automation subscription plan includes a quota of Automation Credits that depletes as you create and execute automations. You can use Automation Credits with MuleSoft Composer, MuleSoft IDP, MuleSoft RPA, Salesforce Flow Orchestration, MuleSoft for Flow: Integration, or a combination of these products. 

The following table shows the conversion rate between Automation Credits and different activities:

[%header%autowidth.spread,cols=".^a,.^a,.^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks | Flow Orchestration Runs | IDP Document Pages | Integration Tasks
| 1 = 80 Automation Credits | 1 = 2 Automation Credits | 1 = 2 Automation Credits | 1 = 100 Automation Credits | 1 = 25 Automation Credits | 1 = 2 Automation Credits
|===

For detailed definitions and more information, see https://www.mulesoft.com/misc/assets/Limited-Release-Features-Entitlements-New-Packaging.pdf[MuleSoft Subscription Plan^].

== Generative AI

The services contain features that use generative AI technology that may be provided by one or more third-parties as listed in the documentation applicable to the services. This documentation provides information and product requirements specific to these generative AI features and providers, including applicable third-party acceptable use policies which the customer must comply with when using the generative AI technology. Due to the nature of generative AI, the output that it generates may be unpredictable, and may include inaccurate or harmful responses. Before using any generative AI output, the customer is solely responsible for reviewing the output for accuracy, safety, and compliance with applicable laws and third-party acceptable use policies. The customer assumes all responsibility for output generated by the services and, as between Salesforce and the customer, such output is customer data.

Einstein supports these predictive models: 

* OpenAI's `GPT-4o (gpt-4o-2024-08-06)` LLM
* OpenAI's `GPT-4o Mini (gpt-4o-mini-2024-07-18)` LLM
* Google's `GEMINI-2.0 Flash 001` LLM

Einstein accesses these models through the Salesforce Einstein Trust layer, which is part of the Salesforce Einstein platform.

Select the model to use during document analysis by clicking *Settings* in the document action editor.  

[NOTE]
Einstein doesn't use customer data to train any models for document analysis in IDP.

include::_partials/see-also.adoc[]
* xref:ms_composer_hyperautomation.adoc[Automation Credits Usage and Rates]