= Invoke a Composer Flow 

Invoke a Composer flow in Flow Builder to enable deeper interoperability and integrated capabilities across Salesforce. For example, use Flow Builder to call an invocable Composer flow that gets real-time credit scores when a user goes through a screen flow.

== Invoke a Composer Flow in Flow Builder

To invoke a Composer flow in Flow Builder, you must:

. <<configure-your-composer-flow,Configure your Composer flow>>.
. <<test-your-invocable-flow,Test your invokable Composer flow.>>
. <<activate-your-invocable-flow,Activate your invocable Composer flow.>>
. <<set-up-salesforce-for-invocable-flows,Set up Salesforce for invocable flows>>.
. <<set-up-flow-builder,Set up Flow Builder>>.

[[configure-your-composer-flow]]
== Configure your Composer Flow

To create a Composer flow, you must: 

. xref:ms_composer_flows.adoc[Build a Composer flow]. 
. xref:ms_composer_test_flows.adoc[Test your Composer flow]. 
. xref:ms_composer_flows.adoc[Activate your Composer flow]. 

[[test-your-invocable-composer-flow]]
== Test Your Invoocable Composer Flow 

[[activate-your-invocable-composer-flow]]
== Activate Your Invoocable Composer Flow 

[[set-up-salesforce-for-invocable-flows]]
== Set Up Salesforce for Invocable Flows

=== Before you begin 
Connect Salesforce org to Anypoint Platform 


https://help.salesforce.com/s/articleView?id=sf.nc_create_edit_external_credential.htm&type=5[create and edit an external credential]

https://help.salesforce.com/s/articleView?id=sf.nc_create_edit_named_credential.htm&type=5[create and edit a named credential]

https://help.salesforce.com/s/articleView?id=sf.external_services_register_json.htm&type=5[oaste the JSON-formatted schema into your browser]

[[set-up-flow-builder]]
== Set Up Flow Bulder

include::_partials/see-also.adoc[]
* https://trailhead.salesforce.com/content/learn/trails/build-flows-with-flow-builder[Trail: Build Flows with Flow Builder]
