= MuleSoft RPA Connector Reference

https://docs.mulesoft.com/rpa-home/[Mulesoft Robotic Process Automation (RPA)] is a software technology that combines robotics and automation to perform repetitive tasks. RPA uses a software bot to mimic the actions a person would take, by automating repetitive manual tasks like entering text and updating fields through one or multiple application user interfaces.

//For more information on metering and billing for Composer and RPA, see xref:ms_composer_task_metering.adoc[MuleSoft Automation Credits].

== RPA Use Cases

You can benefit in many ways by implementing RPA into your processes, either by saving time, reducing costs, or preventing errors caused by human input.

The most common use cases for RPA include:

* Data extraction and data entry +
Extract data from PDF, CSV, and other file formats and send this data to other systems.
* Payroll processing +
Automate payroll data entry and validate the information across multiple systems.
* Price comparisons +
Automate the monitoring of input prices and competitor prices.
* Processing refunds +
Automate the processing of customer refund requests to make them quicker.
* Customer information updates +
Update customer information automatically across different systems that do not have APIs and that are accessible only through the UI.

== Invoke Short-Running RPA Processes

When invoking short-running RPA processes from Composer, invoke a single flow by choosing the *Use response in this flow* button. The RPA execution is retrieved by the RPA step and subsequent steps can use the RPA step datapills.

== Invoke Long-Running RPA Processes

When invoking RPA processes from Composer, a two-flow Composer scenario is only required when the RPA process takes longer than the allowed completion timeout period, which is three minutes.

For long-running processes, you can configure two flows that finish within the Composer flow timeout period to avoid blocking other in-queue events from processing while waiting for the RPA process to complete.

For the first flow, select *Poll response from another flow* and then configure a second RPA poll trigger flow that listens to executions for the process invoked by the first flow. When activating or testing the two-flow scenario, ensure that you start the second poll trigger flow first and then start the invoke flow. This way the poll trigger flow will not miss events generated by the invoke flow.

If data pills from the first RPA invoke flow are needed in the second poll trigger flow, store them in an external database using the *RPA Execution ID* as the key. The data pills are then retrieved when the poll trigger polls the executions from RPA by the *RPA Execution ID*.

If multiple users create invoke or poll flows for the same process, track  execution IDs through the external database. If you are not using an external database to track the process execution, all RPA executions for the selected RPA process complete and the RPA does not filter the executions by user.

== Connections

include::_partials/connection-definition.adoc[]

Connection Display Name::

Enter a connection name to remember the details of this connection. You can reuse connections multiple times in a single flow, and in more than one flow, and the credentials are hidden after you create the connection. Provide a name that easily identifies this connection from others.
+
Only you can see the connection. Other users in your Composer app must create their own connections.

RPA API URL::

The URL provided by the RPA Admin who is creating the processes that you want to integrate via Composer. The *RPA API URL* is the RPA Manager URL with `/rpa/api/v1` appended to it. For example, if your RPA Manager URL is `https://myOrg.rpa.mulesoft.com`, then the value in the *RPA API URL* field is  `https://myOrg.rpa.mulesoft.com/rpa/api/v1`.

API key::

The authentication code for the user. The API key is generated in the https://docs.mulesoft.com/rpa-manager/usermanagement-connect#create-an-api-key-for-a-user[RPA User Management] module.

== Triggers

include::_partials/trigger-definition.adoc[]

RPA Process Execution Completed::

Create listeners that check the status of a specific RPA process. When the RPA process finishes the execution, the polling trigger processes the configured activities in the Composer flow. Note that you must select whether you want listeners for _successful_ or _failed_ executions. You cannot receive notifications for both.

== Actions

include::_partials/action-definition.adoc[]

Invoke RPA Process::

Invokes a process in RPA. Provide a value for *RPA Process Name*. Additionally, select the activity parameters that you want to set and set values for those parameters.

== Test RPA Process

You can test your RPA Process instantly without actually invoking the process.

To test your RPA Process:

. In your RPA Process flow, in an action or trigger, click the gear. +
The *Step Configurations <Action or Trigger>: Invoke RPA Process* window appears.

. In the window, select *Don’t run the RPA Process; instead, use the sample output data* and then click *Save*. +
The RPA Process is skipped and tested. The output of the process appears with sample data.

include::_partials/see-also.adoc[]

* https://docs.mulesoft.com/rpa-home/[Mulesoft Robotic Process Automation (RPA)]
