= HubSpot Connector Reference

HubSpot offers a full platform of marketing, sales, customer service, and CRM software, as well as methodology, resources, and support, to help businesses grow.

== Connections

include::_partials/connection-definition.adoc[]

Connection Display Name::

Enter a connection name that will help you remember the details of this connection.
You can reuse connections multiple times in a single flow, and in more than one flow,
and the credentials are hidden after you create the connection. Therefore, it's helpful
to provide a name that easily identifies this connection from others.
+
Only you can see the connection. Other users in your Composer app must create their own connections.

Bearer token::

The HubSpot account access token.

== Triggers

Each flow starts with a scheduler that specifies a time span for how frequently the flow starts or with a trigger that you define, such as "each time a new record is created." Triggers provide multiple options related to the data in your system.

Triggers execute every fifteen seconds.
//different from the partial - written out here

This system provides the following trigger options:

On New Record::

Triggers when a new Company or Contact record is created.

On New or Updated Record::

Triggers when a new Company or Contact record is created or updated. 

== Actions

include::_partials/action-definition.adoc[]

Create new record::

Create a company or a contact in HubSpot.
+
To create a new company, provide a value for *Company Name*.
+
To create a new contact, provide a value for *Contact Name*.

Update a record::

Update a company or a contact in HubSpot as specified by an external ID.
+
To update a company or a contact, provide a value for *HubSpot ID*.

Create or update record::

Create or update a company or a contact in HubSpot in a single step.
+
To create or update a company, provide a value for *HubSpot ID*.
+
To create or update a contact, provide a value for *External ID Field to Match*.

include::_partials/see-also.adoc[]
