= Slack Connector Reference

Use Slack as a data source or target. For example, you can send a Slack message when a Salesforce opportunity is won.
Some details of how to work with data in a flow are specific to this system, and to the actions you choose.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name::

The Slack workspace name, for example, `my-workspace.slack.com`

Username and password::

The username and password that you use to log in to Slack

== Triggers

include::_partials/trigger-definition.adoc[]

On New Message::

When this trigger fires, new messages are available for subsequent steps.

== Actions

include::_partials/action-definition.adoc[]

Send a direct message to a user::

To post a direct message to a specified user, supply the following information:
+
* *User*: The ID of the user to receive the message.
* *Message*: The message to be sent. You can choose from several options:
    ** Enter text.
    ** Select a data pill.
    ** Select *Custom Expression* to add any combination of text and data pills.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name here for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Post message to channel::

Post a new message to a specific private or public channel that you select. To post a message to a private channel, you must first add the MuleSoft Platform app to that private channel.
+
* *Channel Name*: A channel in the Slack workspace that you select from a drop-down list of the existing channels.
* *Message*: The message to be sent. You can choose from several options:
    ** Enter text.
    ** Select a data pill.
    ** Select *Custom Expression* to add any combination of text and data pills.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Get user by email::

Find a Slack user by entering their email address into the *Email* field.
+
If you want to fetch the user's ID dynamically, you can insert this action, which fetches the Slack user by an email address from another system. Use the *ID* data pill returned by this action to specify the user who should receive the message.

Add users to channel::

Invites users to a channel. This action requires a new connection. Provide a value for the following fields:
+
* *Channel Name*: A channel in the Slack workspace that you select from a drop-down list of the existing channels.
* *User IDs*: IDs of the users to add to a channel.

Create channel::

Creates a public or private channel-based conversation. This action requires a new connection. Provide a value for the following fields:
+
* *Name*: The name of the channel to create.
* *Is Private*: Determines whether the channel to create is private or public.
* *Team Id*: The encoded team ID to create the channel in, which is required if the org token is used.

Send direct message to multiple users::

Sends a direct message to a multi-person direct message channel. Provide a value for the following fields:
+
* *Channel Name*: A channel in the Slack workspace that you select from a drop-down list of the existing channels.
* *Attachments*: At least one attachment for the content of the message.
* *Blocks*: At least one block for the content of the message.
* *Text*: At least one text argument for the content of the message.
* *Icon Emoji*: The emoji to use as the icon for the message. Overrides *Icon Url*. 
* *Icon Url*: The URL to an image to use as the icon for the message.
* *Link Names*: Find and link user groups. 
* *Metadata*: JSON object presented as a URL-encoded string.
* *Mrkdwn*: Disable Slack markup parsing by setting this field to false.
* *Parse*: Change how messages are parsed.
* *Reply broadcast*: Indicates whether the reply is visible to everyone in the channel or conversation. Used in conjunction with *Thread ts*.
* *Thread ts*: Provide another message’s ts value to make this message a reply. Avoid using a reply’s ts value and use its parent’s ts value instead.
* *Unfurl links*: Enable unfurling of primarily text-based content by setting this field to true.
* *Unfurl media*: Enable unfurling of media content by setting this field to true.
* *Username*: Set your bot’s username. 

//Post message to channel::

//When a message is posted to a channel, you can specify a list of attachments to include in the message.

//Sent a direct message to a user::

//When a direct message is sent, you can specify a list of attachments to include in the message.

include::_partials/see-also.adoc[]
