= MuleSoft Automation Credits 1.0

Your MuleSoft Automation subscription plan includes a quota of Automation Credits that you can use with MuleSoft Composer, MuleSoft IDP, MuleSoft RPA, or a combination of these products. As you use processes to create automations, your total credit quota is depleted.

The following table shows the conversion rate between Automation Credits and different activities:

[%header%autowidth.spread,cols=".^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks | IDP Document Pages
| 1 MuleSoft Automation Credit = 2 | 1 MuleSoft Automation Credit = 100 | 1 MuleSoft Automation Credit = 50 | 1 MuleSoft Automation Credit = 5
|===

You can use any combination of these activities, which aggregate over the term of your subscription (not per session), and are then converted to credits as shown. Then, the credits are deducted from your assigned quota for the subscription period.

For detailed definitions and more information, see the https://www.mulesoft.com/prod-subscription-plans[MuleSoft Product Subscription Plans^].

== Usage Summary

The *Usage Summary* page enables you to view your monthly tasks and credit usage per flow for your organization. All Composer users in your organization have access to this page. The monthly summary usage report is usually available five business days after the month close. Reports are available starting from September 2022.

include::_partials/see-also.adoc[]
* xref:ms_composer_hyperautomation.adoc[Automation Credits Usage and Rates]
