= MuleSoft Automation Credits

Your MuleSoft Automation subscription plan includes a quota of Automation Credits that you can use with MuleSoft RPA, MuleSoft Composer, or a combination of both products. As you use processes to create automations, your total credit quota is depleted.

The following table shows the conversion rate between Automation Credits and different activities:

[%header%autowidth.spread,cols=".^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks
| 1 MuleSoft Automation Credit = 2 | 1 MuleSoft Automation Credit = 100 | 1 MuleSoft Automation Credit = 50
|===

MuleSoft adds all the RPA execution times in seconds for the period and converts the total into minutes with two decimal precision. MuleSoft reports Automation Credits with two decimal precision.

For example, if you run 5 processes that take 30 seconds each to execute: MuleSoft converts the total execution time (150 seconds) to minutes, rounds up the last two digits: 150/60 = 2.5 minutes, and then converts the minutes to Automation Credits and rounds up the last two digits: 2.5/2 = 1.25 credits.

You can use any combination of these activities, which aggregate over the term of your subscription (not per session), and are then converted to credits as shown. Then, the credits are deducted from your assigned quota for the subscription period.

For detailed definitions and more information, see the https://www.mulesoft.com/prod-subscription-plans[MuleSoft Product Subscription Plans^].

== Usage Summary

The *Usage Summary* page enables you to view your monthly tasks and credit usage per flow for your organization. All Composer users in your organization have access to this page. The monthly summary usage report is usually available five business days after the month close. Reports are available starting from September 2022.

include::_partials/see-also.adoc[]
