= MuleSoft Automation Credits 2.0

Your MuleSoft Automation subscription plan includes a quota of Automation Credits that depletes as you create and execute automations. You can use Automation Credits with MuleSoft Composer, MuleSoft IDP, MuleSoft RPA, Salesforce Flow Orchestration, or a combination of these products.

The following table shows the conversion rate between Automation Credits and different activities:

[%header%autowidth.spread,cols=".^a,.^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks | Flow Orchestration Runs | IDP Document Pages
| 1 = 80 Automation Credits | 1 = 2 Automation Credits | 1 = 2 Automation Credits | 1 = 100 Automation Credits | 1 = 25 Automation Credits
|===

For detailed definitions and more information, see https://www.mulesoft.com/misc/assets/Limited-Release-Features-Entitlements-New-Packaging.pdf[MuleSoft Subscription Plan^].

include::_partials/see-also.adoc[]
* xref:ms_composer_hyperautomation.adoc[Automation Credits Usage and Rates]