= Slack Connector Reference

Use Slack as a data target. For example, you can send a Slack message when a Salesforce opportunity is won.
Some details of how to work with data in a flow are specific to this system, and to the actions you choose.

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name::

The Slack workspace name, for example, `my-workspace.slack.com`

Username and password::

The username and password that you use to log in to Slack

== Triggers

Use Scheduler to specify when a flow is triggered, for example, every fifteen minutes.

You can't trigger a flow using a connection to Slack.

== Actions

include::_partials/action-definition.adoc[]

Send a direct message to a user::

To post a direct message to a specified user, supply the following information:
+
* *User*: The ID of the user to receive the message.
* *Message*: The message to be sent. You can choose from several options:
    ** Enter text.
    ** Select a data pill.
    ** Select *Custom Expression* to add any combination of text and data pills.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name here for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Create a message::

Post a new message to a specific private or public channel that you select. To post a message to a private channel, you must first add the MuleSoft Platform app to that private channel.
+
* *Channel Name*: A channel in the Slack workspace that you select from a drop-down list of the existing channels.
* *Message*: The message to be sent. You can choose from several options:
    ** Enter text.
    ** Select a data pill.
    ** Select *Custom Expression* to add any combination of text and data pills.
* *Bot Name*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*. You can supply a different name for the messages sent by this action.
* *Bot Icon URL*: By default, the sender of Slack messages generated by an action is *MuleSoft Composer*, and includes the MuleSoft logo in icon form. You can supply a different icon for the messages sent by this action. Specify an icon URL whose access is not restricted.

Get user by email address::

Find a Slack user by entering their email address into the *Email* field.
+
If you want to fetch the user's ID dynamically, you can insert this action, which fetches the Slack user by an email address from another system. Use the *ID* data pill returned by this action to specify the user who should receive the message.

include::_partials/see-also.adoc[]
