= Build a Flow Using Templates

You can create a new flow from a template.

Templates are patterns that you can leverage to build a flow. All of the steps and field mappings are predefined, so you can select the template and enter the missing information for the various connectors used (such as connection secrets) to create a flow you can later customize to meet your business needs. For example, you might still need to add required fields specific to your connection, map additional fields, or add or delete steps to meet your use case. You will likely still need to make a few changes before activating the flow.

Since templates are pre-built flows, templates not only reduce the barrier to entry and accelerate the time to activate the flow, but also include the best practices for flows.

Some examples of templates include:

* Cloud-specific templates, such as Service Cloud or Revenue Cloud
* Connector-specific templates, such as Salesforce, ServiceNow, NetSuite, or Jira

For more information about how to create a new flow from template, refer to xref:ms_composer_flows.adoc#create-a-new-flow-from-template[Create a New Flow From Template].

include::_partials/see-also.adoc[]
