ifeval::["{product}"=="salesforce"]
= MuleSoft Composer for Salesforce: Getting Started
endif::[]
ifeval::["{product}"=="mulesoft"]
= MuleSoft Composer: Getting Started
endif::[]

Check that you meet the listed requirements before you set up Composer. Then you can set up and begin using Composer.

ifeval::["{product}"=="salesforce"]
== Requirements and Restrictions

* The org where you set up Composer must be a Salesforce Unlimited, Enterprise, or Performance edition. It can't be a sandbox org.
* The maximum number of concurrent users supported by an organization is 25.
* The org must have Lightning enabled.
* You must purchase a separate MuleSoft Composer license for the org.
* If your company network has a stringent firewall or list of blocked IP addresses, your network administrator must add `*.mulesoft.com` to the list of allowed addresses.
+
IP addresses used by Composer are dynamic, therefore MuleSoft can't provide a list of IP addresses.
* You must relax any IP restrictions for the connections that you create to data sources and data targets. Instructions are included in the setup section of this topic.
* Composer does not currently support mobile platforms.

=== Browser Requirements:

* Don't use incognito mode or private browsers to access Composer.
* Composer uses Salesforce Canvas and therefore has the same browser requirements as Canvas. For Safari browsers, this means you must uncheck the *Prevent cross-site tracking* option in Safari security preferences.
* When using Firefox or Chrome, you must allow third-party cookies.
* When you create a connection to another system, check for the requirements and limitations listed in the Composer reference section for each connection.
* Composer fields with date values use the following format: YYYY-MM-DDThh:mmZ.

== Set Up Composer

Before anyone can use Composer, a Salesforce admin must set it up, including installation, permissions assignments, and a few adjustments to your Salesforce org settings.

=== Find the Composer Setup Page

. Log in to your Salesforce org as an admin.
. Click the Setup gear icon, and then choose *Setup*.
. Enter `composer` in the search bar.
. Select *MuleSoft Composer* from the search results.
+
If you can't find Composer in the search results, it's likely that your org needs to purchase a license for Composer.

Next, you'll install Composer and make some Salesforce org adjustments to ensure Composer works properly.

=== Admin: Adjust the Session Settings

. In the Salesforce Composer sidebar, click *Settings* > *Security* > *Session Settings*.
. On the *Sessions Settings* page, in the *Session Settings* subsection, deselect the *Lock sessions to the IP address from which they originated* checkbox.
. Click *Save*.

=== Admin: Install Composer and Adjust Salesforce Org Settings

. In the *Install the Managed Package for MuleSoft Composer* section, click *Install Managed Package*.
+
Four more steps are revealed when the installation is complete. As the admin performing the installation, you are automatically given the Composer permission set.

. In the *Change the Type of Permitted Users* section, click *Open Settings* to launch the Salesforce connected app page for Composer and change two settings:
   .. In the *Permitted Users* dropdown, select *Admin approved users are pre-authorized*.
   .. In the *IP Relaxation* dropdown, select *Relax IP restrictions*.
   .. Save the changes.

. In the *Configure MuleSoft Services* section, click *Initiate Configuration*.
+
Salesforce certificates expire after one year. To renew an expired certificate, click *Initiate Configuration*.
+
MuleSoft creates and configures an instance of Anypoint Platform to provide a dedicated environment for Composer.
. In the *Assign Users to MuleSoft Composer* section, click the *Assign Users* button to go directly to the Salesforce *Permission Sets* page:
   .. Click *Composer User*.
   .. Click *Manage Assignments*, and then *Add Assignments*.
   .. Select the checkbox next to each user who will receive permission to use Composer.
   .. Click *Add*. You can assign or revoke this permission set at any time.
. In the *Launch MuleSoft Composer* section, click the *Launch* button to start Composer.

Now that Composer is configured properly, you can launch it by searching for "composer" in the App Launcher.

You can sync data between two Salesforce organizations with a single license. When you set up Composer, you can choose the primary organization in which you want to build flows and then, within Composer in that organization, you can create connections to one or more other Salesforce organizations.

== Users: Verify Access to Composer

If you aren't the Salesforce admin who installed Composer, verify that you have access to the Composer app:

. In your Salesforce org, open the App Launcher.
. Enter `composer` in the search bar.
. Select *MuleSoft Composer* from the search results.
+
If you don't see *MuleSoft Composer* in the search results,
it's likely that you need to purchase Composer for your Salesforce org or that you don't have permission to access it.

When the Composer page displays, you're ready to create your first flow. If you'd like to learn more before using Composer, review the other topics in this section.

== Enable Flow Failure Notifications

As administrator, you can enable flow failure notifications via email. When enabled, checks run every 15 minutes on running flows. If any flow fails, Composer sends an email to the owner of the flow.

//Note that:

//* A maximum of four consecutive emails are sent for the same error.
//* The error log for the flow resets every 24 hours.
//* The error log only runs while the flow runs.

To enable email notifications:

. In the Composer sidebar, click *Settings* > *Email notifications*.
. In the *Receive email notifications when flows fail to run* row, toggle the button to enable email notifications.

endif::[]

ifeval::["{product}"=="mulesoft"]
== Requirements and Restrictions

* The maximum number of concurrent users supported by an organization is 25.
* You must purchase a MuleSoft Composer license, which is sold separately from the Anypoint Platform license.
* If your company network has a stringent firewall or list of blocked IP addresses, your network administrator must add `*.mulesoft.com` to the list of allowed addresses.
+
IP addresses used by Composer are dynamic; therefore, MuleSoft can't provide a list of IP addresses.
* You must relax any IP restrictions for the connections that you create to data sources and data targets as detailed in the Composer setup instructions.
* Composer does not currently support mobile platforms.

=== Browser requirements:
* Don't use incognito mode or private browsers to access Composer.
* If you use Firefox or Chrome, allow third-party cookies.
* When you connect to another system, follow the requirements and restrictions applicable to that connection.
* Composer fields with date values use the format _YYYY-MM-DDThh:mmZ_.

== Set Up Composer

After you purchase MuleSoft Composer, it automatically creates a MuleSoft Composer org for you and sends a welcome email so that you can access MuleSoft Composer for the first time.

After you successfully connect, you then invite users to access that MuleSoft Composer org.

=== Access MuleSoft Composer as for the First Time:

As your organization's primary administrator, follow these steps to initiate your MuleSoft Composer org:

. Log in to your email account, find the welcome email from MuleSoft Composer, and then click *Accept invitation*.
. In the *Create account* form, complete the required fields, including a password of at least eight characters that contains at least one uppercase letter, one lowercase letter, and one number.
. Click *Create account*.
. Log in to MuleSoft Composer using the username and password you just created.
. In *Register a Verification Method*, select a verification method, follow the steps to set up your multi-factor authentication, and then click *Connect*. +
The MuleSoft Composer overview page appears.

=== Invite Users to Access MuleSoft Composer

After you access your MuleSoft Composer org using administrator credentials, you then invite your organization's users to your new MuleSoft Composer account:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, click *Add Users*.
. In the *Invite New Users* window, enter the email addresses of the users you want to invite, separating the names by using commas.
. Select the permissions that you want to apply to that group of users and then click *Invite*.
+
The following permissions are available:

* *Builder*: Enables all users in the group to create and manage flows.
* *Administrator*: Enables all users in the group to invite and manage users in addition to creating and managing flows.
+
The invited users receive the MuleSoft Composer welcome email.

=== Monitor Pending Unaccepted Invitations

After inviting users, you can monitor each pending invitation that has not yet been accepted.

To monitor a pending invitation:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, elect the *Pending Invitations* tab. +
Information about the users' invitations appear. In the menu:
.. Click the options icon to the right of the user invitation that you want to monitor.
.. If the invitation to that user is older than 14 days and is about to expire, if you want to resend it, click *Resend Invite*.
.. If you want to revoke the invitation to that user, click *Revoke Invite*.

== Admin: Manage Users

As administrator, you are responsible for managing your MuleSoft Composer users to meet your organization’s business needs. The following user management tasks are available:

* Change user roles
* Reset user passwords
* Reset user multi-factor authentication (MFA) methods
* Delete users

=== Change User Roles

To change a user's role:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, next to the user's email address, click the options icon and then click *Manage*. +
The user's page appears.
. Select the *Permissions* tab.
. Select the permission setting for the user and then click *Save*.

=== Reset User Passwords

To reset a user's password:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, next to the user's email address, click the options icon, and then click *Reset Password*. +
An email is sent to the user with instructions for resetting their MuleSoft Composer MFA settings.

=== Reset User Multi-factor Authentication (MFA) Methods

To reset a user's MFA method:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, next to the user's email address, click the options icon,
 and then click *Reset Multi-factor Auth*. +
An email is sent to the user with instructions for resetting their MuleSoft Composer password.

=== Delete Users

To delete a user:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Users*.
. On the *Users* page, next to the user's email address, click the options icon, and then click *Delete*. +
A message appears, warning you that deleting a user cannot be undone.
. Click *Delete*.

=== Enable Multiple Identification Providers (IDP)

As an administrator, you can enable users to add identity providers (IDPs) for their organization. Note that:

* If an IDP user is deleted from MuleSoft Composer and that user subsequently logs in to MuleSoft Composer using the IDP, the user profile is restored in the `Disabled` state. To allow the user to authenticate again, an toggle the state to `Enabled`.
* You cannot disable the creation of new users via the *Users* page.
* Deleting an IDP user does not stop the flows activated by that user.
* When MuleSoft Composer is dynamically registered as an OpenID Connect SSO provider in Okta, MuleSoft Composer is named “Anypoint Platform” in Okta.

For more information on identity management in MuleSoft, see the xref:access-management::external-identity.adoc[Access Management] documentation.

To enable OpenID Connect (OIDC) IDP:

. In the MuleSoft Composer sidebar, click *Settings* and then click *Multiple IDP*.
. On the *Identity Provider* page, click *Add Identity Provider* > *OpenID Connect*.
. In the *New Identity Provider* page, complete the required fields:
+
* *Name*: The nickname for this IDP.
* *Client Registration URL*: The URL to dynamically register client applications for your identity provider. This field appears when you select *Dynamic Registration*.
* *Authentication Header*: The header that provides credentials to authenticate a server. This header is required if the provider restricts registration requests to authorized clients. This field appears when you select *Dynamic Registration*.
* *Client ID*: The unique identifier that you provided for your manually created client application. This field appears when you select *Manual Registration*.
* *Client Secret*: The password, or secret, for authenticating your MuleSoft Composer organization with your Identity Provider. This field appears when *Manual Registration* is selected.
* *OpenID Connect Issuer*: The location of the OpenID Provider. For most providers, `.well-known/openid-configuration` is appended to the issuer to generate the metadata URL for OpenID Connect specifications. If your OpenID Provider is Salesforce, then you must provide the value for `issuer`.
* *Authorize URL*: The URL where the user authenticates and grants OpenID Connect client applications access to the user's identity.
* *Token URL*: The URL that provides the user’s identity encoded in a secure JSON Web Token.
* *User Info URL*: The URL that returns user profile information to the client app.

. Optionally, expand *Advanced Settings*, and provide the following values:
+
* *Group Scope*: The OIDC scope to request the group claim.
* *Group Attribute JSON Data Expression*: The JSONata expression used to select the groups from the user information or ID token. The result must be an array of strings.
* *Disable server certificate validation* checkbox: Select to disable server certificate validation if your OpenID client management instance presents a self-signed certificate or one signed by an internal certificate authority.

. Click *Save*.
. Log out of MuleSoft Composer, navigate to the sign-on URL you entered in the *New Identity Provider* page, and then log in through your identity provider to test the configuration.

To enable SAML 2.0 IDP:

Note that the file-based configuration of a SAML 2.0 is not supported.

. In the MuleSoft Composer sidebar, click *Settings* and then click *Multiple IDP*.
. On the *Identity Provider* page, click *Add Identity Provider* > *SAML 2.0*.
. In the *New Identity Provider* page, complete the required fields:
+
* *Name*: Enter a nickname for this IDP.
* *Sign On URL*: The redirect URL provided by the IDP for sign in. For example, `\https://example.com/sso/saml`.
* *Sign Off URL*: The URL to redirect sign-out requests, so users both sign out of MuleSoft Composer and have their SAML user’s status set to `signed out`.
* *Issuer*: The ID of the identity provider instance that sends SAML assertions.
* *Public Key*: The Public key provided by the identity provider, which is used to sign the SAML assertion. It is the `X509Certificate` value in the SAML response.
* *Audience*: An arbitrary string value that identifies your MuleSoft Composer organization. The typical value for this string is `<organizationDomain>.composer.mulesoft.com`.
* *Single Sign On Initiation*: Specify whether SSO can be initiated by MuleSoft Composer, your identity provider (for example, Okta), or both.

** The *Service Provider Only* option allows only MuleSoft Composer to initiate SSO.
** The *Identity Provider Only* option allows only your external identity provider to initiate SSO.
** The *Both* option allows either MuleSoft Composer or your external identity provider to initiate SSO. +
The default value for this setting for newly configured identity provider configurations is *Both*.

. Optionally, expand *Advanced Settings*, and provide the following values:
+
* *Username Attribute*: Field name in the SAML `AttributeStatements` that maps to the user's name. If no value is configured, the `NameID` attribute of the SAML `Subject` is used (Note: This is outside the SAML `AttributeStatements`).
* *First Name Attribute*: Field name in the SAML `AttributeStatements` that maps to `First Name`.
* *Last Name Attribute*: Field name in the SAML `AttributeStatements` that maps to `Last Name`.
* *Email Attribute*: Field name in the SAML `AttributeStatements` that maps to `Email`.
* *Group Attribute*: Field name in the SAML `AttributeStatements` that maps to `Group`.
* *Require encrypted SAMl assertions* checkbox: If enabled, the SAML assertions sent from the IDP must be encrypted and follow the guidelines mentioned in the prerequisites.

. Click *Save*.
. Log out of MuleSoft Composer, navigate to the sign-on URL you entered in the *New Identity Provider* page, and then log in through your identity provider to test the configuration.

== Enable Flow Failure Notifications

As administrator, you can enable flow failure notifications via email. When enabled, checks run every 15 minutes on running flows. If any flow fails, Composer sends an email to the owner of the flow. Note that:

* A maximum of four consecutive emails are sent for the same error.
* The error log for the flow resets every 24 hours.
* The error log only runs while the flow runs.

To enable email notifications:

. In the Composer sidebar, click *Settings* and then click *Email notifications*.
. Toggle the button to enable email notifications.
. Click *Save*.

[[connect-composer-to-anypoint-platform]]
== Connect Composer to Anypoint Platform

Organizations that use both MuleSoft Composer and Anypoint Platform can connect the two products.

To link Composer to Anypoint Platform:

. In MuleSoft Composer, in the left pane, click *Settings* > *Account*. +
The *Account* page appears.

. On the *Account* page, copy the value in the *Organization ID* field.

. Log in to the Anypoint Platform organization that you want to connect to MuleSoft Composer. +
The *Anypoint Platform* page appears.

. In the left pane, click xref:access-management::managing-your-account.adoc[*Access Management*]. +
The *Access Management* page appears.

. In the *Access Management* page, in the left pane, click *Composer Sync*. +
The *Add Composer Organization* window appears.

. In the *Add Composer Organization* window, in the *Organization ID* field, paste the *Organization ID* that you copied from the *Account* page of MuleSoft Composer and then click *Add*.

. Open MuleSoft Composer and refresh the page.

. In MuleSoft Composer, in the left pane, click *Settings* > *Account*. +
The *Account* page appears, displaying a linking request from Anypoint Platform.

. Click *Review and Confirm*.

. In the *Access Token* section, click *Authenticate in Anypoint*. +
The Anypoint Platform login page appears.

. Log in to Anypoint Platform.

. In the *Client App* section, click *Create Client App*. +
The Composer organization is now linked to the Anypoint organization.

== API Sharing

MuleSoft Anypoint Platform customers can share externally available APIs managed in Anypoint Platform with business users for consumption in a MuleSoft Composer flow.

Before sharing APIs from Anypoint Platform to MuleSoft Composer, ensure that:

* Your organization uses Anypoint Platform for API Management.
* Your organization has xref:exchange::to-create-an-asset.adoc#create-an-api-asset[Rest APIs] managed by API Manager that conform to the following:

** API specifications use either RAML or OpenAPI
** API uses basic authentication, bearer token, or API Key in conjunction with a Client ID and Secret

* Composer organizations are <<connect-composer-to-anypoint-platform,linked to Anypoint organizations>>.
* API must be accessible from the public internet.

=== Share an API Instance with Composer

If you manage your APIs with Anypoint API Manager, you can share those APIs with MuleSoft Composer.

To share an API Instance with MuleSoft Composer:

. xref:2.x@api-manager::create-instance-task.adoc[Create an API Instance in Anypoint Platform].

. In Anypoint Platform, in the left pane, click *Exchange*.

. In the list, find the API instance that you want to share, click *Request access*, and then click the Client App that was created by MuleSoft Composer. +
The *Request access* window appears.

. In the *Request access* window, click *Request access*.

. Open MuleSoft Composer and then open the flow to ensure that the shared API appears in the *Shared Apps* section of the canvas.

=== Disconnect Composer Connection to Anypoint Platform

You can disconnect your connection from MuleSoft Composer to Anypoint Platform; however, removing this connection does not delete existing configurations.

To disconnect your MuleSoft Composer connection to Anypoint Platform:

. Log in to the Anypoint Platform organization containing the connection to MuleSoft Composer that you want to disconnect. +
The *Anypoint Platform* page appears.

. In the left pane, click xref:access-management::managing-your-account.adoc[*Access Management*]. +
The *Access Management* page appears.

. In the left pane, click *Connected Apps*. +
The *Connected Apps* page appears.

. In the *Owned Apps* tab, next to *Composer API Sharing*, click the options button, and then click *Delete*. +
MuleSoft Composer is now disconnected from Anypoint Platform.

endif::[]

ifeval::["{product}"=="salesforce"]
== Related Resources

* xref:ms_composer_overview.adoc[Overview]
* xref:ms_composer_reference.adoc[Composer Connector Reference]
* https://help.salesforce.com/s/search-result?language=en_US&f%3A%40sflanguage=%5Bes%5D&sort=relevancy&f%3A%40sfkbdccategoryexpanded=%5BAll%5D&t=allResultsTab#t=allResultsTab&sort=date%20descending&f:@objecttype=%5BKBKnowledgeArticle%5D&f:@sflanguage=%5Ben_US%5D&f:@sfkbdccategoryexpanded=%5BAll,MuleSoft%20Composer%5D[Knowledge Articles]
* https://developer.salesforce.com/docs/atlas.en-us.platform_connect.meta/platform_connect/canvas_framework_supported_browsers.htm[Salesforce Canvas browser support]
endif::[]

ifeval::["{product}"=="mulesoft"]
== Related Resources

* xref:ms_composer_overview.adoc[Overview]
* xref:ms_composer_reference.adoc[Composer Connector Reference]
* https://help.mulesoft.com/s/global-search/%40uri#t=SalesforceArticle&f:@sfdcproduct=%5BMuleSoft%20Composer%5D[Knowledge Articles]
endif::[]
