= Jira Connector Reference

Jira is a powerful project management tool and ticketing system used to help users plan, track, release, and report product issues in order to improve development.

To use Jira Connector with Composer, you must have the _Administrator Jira_ global permission. For more information, see the https://support.atlassian.com/jira-work-management/docs/manage-permissions/[Jira documentation].

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Username::

The OAuth username that you use to log in to Jira.

Password::

The OAuth password that you use to log in to Jira.

== Triggers

include::_partials/trigger-definition.adoc[]

New issue with Custom Fields::

Checks for a new issue with Custom fields created in Jira.

New issue with Standard Fields only::

Checks for a new issue with Standard fields created in Jira.

Update issue with Custom Fields::

Checks for updated issues with Custom fields in Jira.

Update issue with Standard Fields only::

Checks for updated issues with Standard fields in Jira.


== Actions

include::_partials/action-definition.adoc[]

Create issue with custom fields::

Creates a new issue within the selected project. Provide a value for the following fields:

* *Project*
* *Key*
* *Summary*
* *Type*
* *Status*
* *Priority*

Update issue with custom fields::

Updates specified Custom field values. Provide a value for the following fields:

* *Issue ID or Key*
* *Notify Users*

Update issue with standard fields only::

Updates specified Standard field values. Provide a value for the following fields:

* *Issue ID or Key*
* *Notify Users*

Assign user to issue::

Assigns a user to a specified issue. Provide a value for *Issue ID or Key*.

Add watcher to issue::

Adds a watcher to an existing Jira issue. Provide a value for *Issue ID or Key*.

Get issue::

Returns details for a specific issue. Provide a value for *Issue ID or Key*.

Add comment to issue::

Creates and adds a comment to an existing issue. Provide a value for the following fields:
* *Issue ID or Key*
* *Comment Text*

Get account IDs for users::

Returns the account IDs for the users specified in the `key` or `username` parameters. You can specify multiple `key` or `username` parameters.

== Custom Fields

Using MuleSoft Composer, you can access Standard  custom field values in Jira for actions and triggers that you set in the Jira issue.

include::_partials/see-also.adoc[]
