= Sage Intacct Connector Reference

Sage Intacct is a best-in-class enterprise resource planning solution built to create and automate important financial processes and enable real-time visibility into business performance.

== Prerequisites

To use the Sage Intacct Connector in Composer, you must first complete the following actions within Sage Intaact to complete the integration with Composer:

* https://developer.intacct.com/web-services/[Subscribe to Web Services] to allow Composer to interact with the Sage Intaact API.
* https://developer.intacct.com/web-services/[Add your company’s *Sender ID* to the allowed list]. The *Sender ID* identifies Composer to the Sage Intaact API.
* If you are using role-based permissions, you must https://developer.intacct.com/api/company-console/roles/[create a new role and provide the required permissions for that role].

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Company ID::

The customer Company ID. In the field, enter the ID of your Sage Intaact instance. For more information, see the https://developer.intacct.com/web-services/[Sage Intaact documentation].

User ID::

The user ID that you use to log in to Sage Intacct.

User Password::

The password that you use to log into Sage Intacct.

Entity ID::

The entity to which you want to connect. To connect to the top level of the company, leave this field blank. For more information, see the https://developer.intacct.com/api/company-console/api-sessions/[Sage Intaact documentation].

== Triggers

include::_partials/trigger-definition.adoc[]

New customer::

Checks for a new customer record.

New or updated customer::

Checks for new or updated customer record.

New order::

Checks for a new order record.

New or updated order::

Checks for a new or updaded order record.

== Actions

include::_partials/action-definition.adoc[]

Create customer::

Create a new customer record. Provide a value for the following:

* *Customer ID*
* *Primary Contact*
* *Print as*

Update customer::

Update a customer record. Provide a value for *ID*.

Get customer::

Returns a list of customer records. Provide a value for *Customer ID* or *Customer Name*.

Create order::

Create a new order record and returns a value for the *Key* field. Provide a value for the following:

* *Order Type*
* *Date Created*
* *Transaction Currency*
* *Base Currency*
* *Exchange Rate Type*
* In the *Entries* > *Sotransitem* section, provide a value in the following:
  ** *Sotransitem List*
  ** *Item ID*
  ** *Quantity*
  ** *Location ID* +

Note that the *Location ID* field is determined by the numbers preceding the location description. For example, if the Location ID is `100-United States` then enter `100` in the *Location ID* field.

  ** *Price*
  ** *Unit*
  ** If your order contains inventory type items or a mix of inventory and non-inventory items, provide a value for *Warehouse ID*.

Update Order::

Updates a customer record. Provide a value for the following:

* *Document ID* +

Note that the *Doc ID* value is the *Key* value returned by the *Create Order* action.

*  In the *Entries* > *Updatesotransitem* > *Line number* section:
** If the source list _contains_ a matching Sage Intacct line item, the Sage Intacct line item is _updated_.
** If the source list _does not_ contain a matching Sage Intacct line item, the Sage Intacct line item is _deleted_.
** If the source list contains a line item that _does not exist_ in Sage Intacct, the line item is _created_. +

Note that when reordering a line item, the line order can change. For example, if you drag a line item from the number two position to the number three position in the Sage Intaact UI, the line order changes.To avoid synchronizing the wrong Sage Intacct order line item, you must account for possible order line item changes.

Get Order::

Returns a list of order records. Provide a value for one of the following fields:

* *Order ID*
* *Customer ID*
* *Document ID* +

Note that the *Document ID* value is the *Key* value returned by the *Create Order* action.

Create product::

Create a new product record and returns the *Item ID* and *Record Number*. Provide a value for the following:
* *Item ID*
* *Name*
* *Item Type*

== Custom Fields

If your Composer flow automation requires custom fields, please see the https://developer.intacct.com/customization-services/#custom-fields[Sage Intacct documentation].

include::_partials/see-also.adoc[]
