= Snowflake Connector Reference

Snowflake is a fully managed, cloud-based data warehouse solution that operates under a Software as a Service (SaaS) business model. This allows clients to store data and run analytics without the need for an on-premise solution.

== Connections

include::_partials/connection-definition.adoc[]

Connection Name::

Enter a connection name that will help you remember the details of this connection.
You can reuse connections multiple times in a single flow, and in more than one flow,
and the credentials are hidden after you create the connection. Therefore, it's helpful
to provide a name that easily identifies this connection from others.
+
Only you can see the connection. Other users in your Composer app must create their own connections.

Username and password::

The username and password that you used to log in to Salesforce. You’ll need to create a connection even if the data source is the same Salesforce org where you operate Composer. However, Composer won’t ask for your password again. Instead, it displays an authentication approval dialog.

Account Name::

The account name that is provided when registering for the Snowflake account.

Warehouse::

The name of the Snowflake warehouse to use.

Database::

The Snowflake database to connect to.

Schema::

The Snowflake database schema to use.

== Triggers

include::_partials/trigger-definition.adoc[]

On New Row::

Returns all new rows of a table based on a watermark every 15 seconds. Provide a value for the following fields:

* *Table*
* *Watermark Column*

On New or Updated Row::

Returns all new or updated rows of a table based on a watermark every 15 seconds. Provide a value for the following fields:

* *Table*
* *Watermark Column*
* *Update Watermark Column*

== Actions

include::_partials/action-definition.adoc[]

Insert Rows::

Updates a table by inserting one or more rows into the table. Provide a value for *Query*.

Update Rows::

Updates a set of rows. Provide a value for *Query*.

Delete Rows::

Deletes a set of rows. Provide a value for *Query*.

Select Rows::

SELECT can be used in both a statement and a clause within a SELECT statement. As a statement, the SELECT statement is the most commonly executed SQL statement; it queries the database and retrieves a set of rows. As a clause, SELECT defines the set of columns returned by a query. Provide a value for *Query*.

include::_partials/see-also.adoc[]
