= MuleSoft Automation Credits 2.0

A quantity of Automation Credits is included with certain MuleSoft Services, with the specific entitlement indicated on the Usage Details table on the Order Form for such Services. Automation Credits are consumed as you create and execute automations at the applicable multiplier rates based on the Usage Types in the following table. You can use Automation Credits with MuleSoft Composer, MuleSoft IDP, MuleSoft RPA, Salesforce Flow Orchestration, MuleSoft for Flow: Integration, or a combination of these products as more fully described in the applicable https://www.salesforce.com/company/legal/mulesoft-subscription-plan/[Subscription Plan] or https://www.salesforce.com/en-us/wp-content/uploads/sites/4/documents/legal/Agreements/Limited-Release-Features-Entitlements-New-Packaging.pdf[Features and Entitlement Document].

[%header%autowidth.spread,cols=".^a,.^a,.^a,.^a,.^a]
|===
| RPA Bot Minutes | RPA API Calls | Composer Tasks | Flow Orchestration Runs | IDP Document Pages | Integration Tasks
| 1 = 80 Automation Credits | 1 = 2 Automation Credits | 1 = 2 Automation Credits | 1 = 100 Automation Credits | 1 = 25 Automation Credits | 1 = 2 Automation Credits
|===

[IMPORTANT]
Beginning October 24, 2025, the multiplier for IDP Document Page will change to `30 Automation Credits`.

To learn more about how Flex Credits are consumed, and when other types of credits are consumed with generative AI features, please visit: https://help.salesforce.com/s/articleView?id=ai.generative_ai_usage.htm&type=5[Agentforce and Generative AI Usage and Billing] in Salesforce Help.

include::_partials/see-also.adoc[]
* xref:ms_composer_hyperautomation.adoc[Automation Credits Usage and Rates]