= Hyperautomation Package 

The Hyperautomation Package enables you to log in to Anypoint Platform to access  MuleSoft Composer, MuleSoft Anypoint Platform, xref:rpa-home::index.adoc[MuleSoft Robotic Process Automation (RPA)], and https://help.salesforce.com/s/articleView?id=sf.orchestrator_flow_orchestrator.htm&type=5[Salesforce Flow Orchestrator]. 

With the Hyperautomation Package, the following Anypoint Platform features are available to Composer users: 

* xref:access-management::audit-logging.adoc[Anypoint Audit Logging]
* xref:exchange::index.adoc[Anypoint Exchange] 
* xref:visualizer::index.adoc[Anypoint Visualizer] 
* xref:monitoring::index.adoc[Anypoint Monitoring] 

For more information about the pricing and contents of each hyperautomation package, please see <WHATEVER MARKETING PAGE>

== Access Composer with Hyperautomation Package 

=== Admin: Grant Access to Composer Users 

To access a single tenant org, the Anypoint Admin must first: 

. Create an xref:access-management::managing-your-account.adoc[Anypoint Platform Account] for the users.
. Grant one of the following xref:ms_composer_prerequisites.adoc#change-user-roles[roles] to each user: 
.. *Composer Base User*: This user can create and manage their own flows. 
.. *Composer Super User*: This user can create and manage their own flows and they can also take ownership of any flows in the Anypoint Composer org. Note that the following Composer features are are only available to those with the Composer Super User role: 

... API Sharing 
... Flow Sharing
... Usage Summary 

=== Access Composer with the Hyperautomation Package  

To access Composer with the Hyperautomation Package: 

. Log in to Anypoint Platform. 
. On the *Anypoint Platform* page, click *Go to Composer*.  

include::_partials/see-also.adoc[]