= Xero Connector Reference

Xero is a SaaS-based accounting application used primarily by small to medium sized businesses for accounting functions such as invoice creation and tracking, receiving and tracking payments, managing inventory, storing customer contacts, and creating purchase orders and quotes.

== Connections

include::_partials/connection-definition.adoc[]

To establish a connection from Composer to Xero, you must select the Xero Organization to which you want to connect in the *Organization* field.

include::_partials/connection-name.adoc[]

Username::

The OAuth username that you use to log in to Xero.

Password::

The OAuth password that you use to log in to Xero.

== Triggers

Each flow starts with either a _scheduler_ or a _trigger_. Schedulers are set to a default frequency of 15 minutes. Triggers, such as "each time a new record is created", are defined by you and provide multiple options related to the data in your system.

Triggers use a polling process to actively check for new updates from an external system. The polling frequency five minutes. 

This system provides the following trigger options:

New or updated Contact::

Checks for a new or updated contact record. Provide a value for the following fields:

* *Organization*
* *Contact Type*

New or updated item::

Checks for a new or updated item record. Provide a value for the following fields:

* *Organization*
* *Is purchased*
* *Is sold*
* *Is tracked as inventory*

New or updated payment::

Checks for a new or updated payment. Provide a value for the *Organization* field.

On New or Update Invoice::

Checks for a new or updated invoice. Provide a value for the following fields:

* *Organization*
* *Invoice type*
* *Invoice status*

== Actions

include::_partials/action-definition.adoc[]

Create or update contact::

Creates a new contact record nor updates an existing contact record. Provide a value for the following fields:

* *Organization*
* *Contact name*
* If you add additional contacts, you must also provide a value for *Email address*.

Search contacts::

Returns a list of contact records based on values entered. Provide a value for *Organization*.

Get contact by ID::

Returns a single contact record based on the ID value. Provide a value for the following fields:

* *Organization*
* *Contact ID*

Create or update invoice::

Creates or updates an invoice record. Only direct columns within Invoice are supported. Provide a value for the following fields:

* *Organization*
* *Invoice type*
* *Contact name*
* *Items*

Update invoice headers::

Updates specific fields in an invoice record. Provide a value for the following fields:

* *Organization*
* *Invoice Reference Type*
* *Invoice Reference*

//Create Item::

//Creates an item record. Provide a value for the following fields:

//* *Organization*
//* *Item Code*
//* If a value is specified in the *Inventory Asset Account Code* field, then a value is required in the *Purchase Account Code* field.

Create or update item::

Creates or updates a field in the item record. Provide a value for the following fields:

* *Organization*
* *Item Code*

Get Invoices::

Returns new or updated invoice records. Provide a value for *Organization*.

== Objects

The Action: *Create or update invoice* object is available.

//* Field: *Contact persons*

== Custom Fields 

Custom fields are not supported. Using MuleSoft Composer, you can access standard field values for actions and triggers that you set in the Xero record.

include::_partials/see-also.adoc[]
