= Quickbooks Online Connector Reference

QuickBooks Online provides cloud-based accounting software that enables organizations to manage core business processes, ERP financials, e-commerce, inventory, and more.

QuickBooks Online Connector uses https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api/minor-versions[API minor version 62].

== Connections

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Username::

The OAuth username that you use to log in to QuickBooks Online.

Password::

The OAuth password that you use to log in to QuickBooks Online.

== Triggers

include::_partials/trigger-definition.adoc[]

New Invoice::

Triggers when a new invoice is created.

New or Updated Invoice::

Triggers when an invoice is created or when an existing invoice is updated.

New Customer::

Triggers when a new customer is created.

New or Updated Customer::

Triggers when a customer is created or when an existing customer is updated.

New Item::

Triggers when a new item is created.

New or Updated Item::

Triggers when an item is created or when an existing item is updated.

New Estimate::

Triggers when an estimate is created.

New or Updated Estimate::

Triggers when an estimate is created or when an existing estimate is updated.

=== Polling Frequency 

include::_partials/polling-frequency.adoc[]

== Actions

include::_partials/action-definition.adoc[]

Create Invoice::

Creates a new invoice. Provide a value for *Customer ID*.

Update Invoice::

Updates an existing invoice. Provide a value for *Invoice ID*.

Create Customer::

Creates a new customer.

Update Customer::

Updates an existing customer. Provide a value for *Customer ID*.

Create Item::

Creates a new item. The following fields are required:

* *Name*
* *Type*
* If the value in the *Track Quantity on Hand* is equal to `True`, the following fields are required:
** *Asset Account Reference*
** *Invoice Start Date*
** *Quantity on Hand*

Update Item::

Updates an existing item. The following fields are required:

* *Item ID*
* If the value in the *Track Quantity on Hand* is equal to `True`, the following fields are required:
** *Asset Account Reference*
** *Invoice Start Date*
** *Quantity on Hand*

Query Invoice::

Searches for an existing invoice. One or more of the following fields must be populated to return results:

* *Invoice ID Equals*
* *Customer ID Equals*
* *Due Date Greater Or Equal*
* *Date Created Greater or Equal*
* *Last Updated Date Greater or Equal*

Query Customer::

Searches for an existing customer. One or more of the following fields must be populated to return results:

* *Customer ID Equals*
* *Customer Display Name Equals*
* *Customer Display Name Like*
* *Active Equals*
* *Primary Email Address Equals*
* *Primary Email Address Like*
* *Balance Greater Or Equal*
* *Date Created Greater or Equal*
* *Last Updated Date Greater or Equal*

Query Item::

Searches for an existing item. One or more of the following fields must be populated to return results:

* *Item ID Equals*
* *Name Equals*
* *Name Like*
* *Active Equals*
* *Type Equals*
* *Date Created Greater or Equal*
* *Last Updated Date Greater or Equal*

Get Invoice::

Returns an invoice. Provide a value for *Customer ID*.


Get Customer::

Returns a customer.  Provide a value for *Customer ID*.

Get Item::

Returns an item. Provide a value for *Item ID*.

Create Estimate::

Creates an estimate record. Provide a value for the following fields:

* *Customer ID*
* *Estimate Parameters*

Get Estimate::

Returns an estimate. Provide a value for *Estimate ID*.

Update  Estimate::

Updates the estimate record. Provide a value for the following fields:
* *Estimate ID*
* *Estimate Parameters*

== Custom Fields

Using MuleSoft Composer, you can access custom field values for actions and triggers that you set in the Quickbooks Online record.

Note that the QuickBooks Online API only returns the first three custom fields created for the type `string`. Any subsequent custom string fields or any fields of another data type, such as `date` or `picklist`, are not writable fields within Composer. For more information, see the https://developer.intuit.com/app/developer/qbo/docs/workflows/create-custom-fields[Quickbooks Online documentation].

include::_partials/see-also.adoc[]
