= Salesforce Marketing Cloud Connector Reference

Salesforce Marketing Cloud is a marketing platform that supports capabilities such as real-time customer engagement, email and marketing automation, social media engagement, mobile (SMS) messaging and push notifications, and customer marketing analytics.

== Create Package and Permissions

To use the Salesforce Marketing Cloud Connector, you must first create packages and permissions. 

To create packages and permissions:

. In Composer, click the gear icon in the upper right corner. +
The *Setup* page appears.
.  In the navigation pane, under *Platform Tools*, click *Apps* > *Packaging* > *Installed Packages*. +
The *Installed Packages* page appears.
.

== Connections

To connect to a system, whether it is a source of data or the target where you are sending data, you must create a connection with that system's required credentials. You typically connect to different systems within a flow and can reuse each connection every time you need to connect.

For more information on how to create an API integration in Installed Packages, refer to https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/integration-s2s-client-credentials.html[Server-to-Server Integrations with Client Credentials Grant Type].

This system requires the following credential information for its connections:

Connection Display Name::

Enter a connection name that will help you remember the details of this connection.
You can reuse connections multiple times in a single flow, and in more than one flow,
and the credentials are hidden after you create the connection. Therefore, it's helpful
to provide a name that easily identifies this connection from others.
+
Only you can see the connection. Other users in your Composer app must create their own connections.

Client ID::

Enter the Client ID from the Installed Package.

Client Secret::

Enter the Client Secret from the Installed Package.

Authentication URI::

Enter the Authentication Base URI from the Installed Package.

Scopes::

(Optional) Enter the scopes MuleSoft Composer should have access to. This is helpful if your package has access to a larger number of scopes than are needed here.
Minimum scope required: offline, email_send, sms_send, list_and_subscribers_read

== Actions

include::_partials/action-definition.adoc[]

Send email::

Sends an email to the customer using a specific template. Provide a value for the following fields:

* Email Definition
* Contact Key
* Email

Send SMS::

Sends an SMS to the customer using a specific template. Provide a value for the following fields:

* SMS Definition
* Contact Key
* Recipient’s Phone Number

include::_partials/see-also.adoc[]
