==== JIRA

* The following standard fields are not supported at this time:

** *Affects version*
** *Fix version*
** *Environment*
** *Component*

* Custom fields containing the following list components are failing to render:

** *Text field (multi-line)*
** *Labels*
** *Checkboxes*
** *Radio Buttons*
** *Select list (multiple-choice)*
** *Select list (cascading)*

* In the *Status* field, the *In Progress* value sometimes appears twice. If so, test both *In Progress* values to find the working value.

* After creating a case in JIRA, the *Update issue* action does not update the value in the *Reporter* field. Additionally, the value in this field must be blank for the *Update issue* action to succeed. To update the value in the *Reporter* field, you can manually update the case record in JIRA.

* If custom fields fail to appear, reset your JIRA connection by deleting the connection and re-authenticating your JIRA account.

* When you create an issue, you may encounter a 400 error in the output metadata. Disregard this error.
