= MuleSoft Automation のクレジット

MuleSoft Automation サブスクリプションプランには、MuleSoft RPA、MuleSoft Composer、または両製品の組み合わせで使用可能な自動化クレジットのクォータが含まれています。プロセスを使用して自動化を作成するたびに、クレジットクォータの合計から差し引かれます。

自動化クレジットとさまざまなアクティビティの間の換算率を次の表に示します。

[%header%autowidth.spread,cols=".^a,.^a,.^a]
|===
| RPA Bot の分数 | RPA API コール | Composer タスク
| 1 MuleSoft Automation のクレジット = 2 | 1 MuleSoft Automation のクレジット = 100 | 1 MuleSoft Automation のクレジット = 50
|===

MuleSoft は、期間のすべての RPA 実行時間 (秒単位) を加算し、合計を小数第 2 位の精度で分数に変換します。MuleSoft は、小数第 2 位の精度で自動化クレジットをレポートします。

たとえば、それぞれの実行に 30 秒かかる 5 個のプロセスを実行した場合、MuleSoft は合計実行時間 (150 秒) を分に変換して最後の 2 桁で丸め (150/60 = 2.5 分)、この分を自動化クレジットに変換して最後の 2 桁で丸めます (2.5/2 = 1.25 クレジット)。

これらのアクティビティの任意の組み合わせを使用できますが、これらはサブスクリプションの期間中に集計され (セッションごとではありません)、ここで示しているクレジットに換算されます。続いて、クレジットがサブスクリプション期間の割り当てられたクォータから差し引かれます。

詳細な定義と詳細情報は、 https://www.mulesoft.com/prod-subscription-plans[「MuleSoft Product Subscription Plans (MuleSoft 製品サブスクリプションプラン)」^]​を参照してください。

== Usage Summary (利用状況概要)

*[Usage Summary (利用状況概要)]*​ ページでは、組織のフローごとに毎月のタスクとクレジットの利用状況を確認できます。組織内のすべてのコンポーザユーザがこのページにアクセスできます。月次利用状況概要レポートは通常、月の締め日から 5 営業日後に入手できます。レポートは 2022 年 9 月から使用できます。

include::_partials/see-also.adoc[]
