= Snowflake Connector リファレンス

Snowflake は、Software as a Service (SaaS) ビジネスモデルで動作する、完全に管理されたクラウドベースのデータウェアハウスソリューションです。これにより、クライアントはオンプレミスソリューションを必要とせずにデータを保存し、分析を実行できます。

トリガーおよびアクションの権限についての詳細は、 https://docs.snowflake.com/en/user-guide/security-access-control-overview[「アクセス制御の概要」^]​を参照してください。

== 接続

include::_partials/connection-definition.adoc[]

Connection Name (接続名)::

この接続の詳細を把握するのに役立つ接続名を入力します。
1 つのフローおよび複数のフローで接続を複数回再利用できます。接続の作成後、ログイン情報は非表示になります。そのため、この接続を他の接続と簡単に区別できる名前を付けると役立ちます。
+
接続は自分にのみ表示されます。コンポーザーアプリケーションの他のユーザーは、独自の接続を作成する必要があります。

ユーザー名とパスワード::

Snowflake にログインするために使用したユーザー名とパスワード。

Account Name (アカウント名)::

Snowflake アカウントの登録時に指定されたアカウント名。アカウント名は、​`<OrgId>-<AccountId>`​ の形式になります。 

Warehouse (ウェアハウス)::

使用する Snowflake ウェアハウスの名前。

Database (データベース)::

接続する Snowflake データベース。

Schema (スキーマ)::

使用する Snowflake データベーススキーマ。

== データ型

Snowflake Connector では、次のデータ型がサポートされています。

* INT
* NUMBER
* DECIMAL
* BIGINT
* TINYINT
* NUMERIC
* INTEGER
* BYTEINT
* FLOAT
* FLOAT4
* FLOAT8
* DOUBLE
* REAL
* VARCHAR
* CHAR
* CHARACTER
* STRING
* TEXT
* BOOLEAN
* DATE
* DATETIME
* TIMESTAMP
* TIMESTAMP_NTZ

== Triggered (トリガー)

include::_partials/trigger-definition.adoc[]

On New Row::

15 秒ごとにウォーターマークの最大値に基づいてテーブルのすべての新しい行を返します。 
+
新しい行のウォーターマーク値がウォーターマークの最大値よりも小さい場合、新しい行は破棄されます。新しい行のウォーターマーク値がウォーターマークの最大値よりも大きい場合、新しい行が選択され、そのウォーターマークが新しい最大値に設定されます。 
+
フローが手動で非アクティブ化されて再アクティブ化されると、ウォーターマークはフローの開始時刻にリセットされます。フローで開始時刻が指定されていない場合、コンポーザーはフローがアクティブ化された時刻をタイムスタンプとして使用します。
+
次の項目の値を指定します。

* *Table (テーブル)*​: このトリガーでは、​*[Table (テーブル)]*​ 項目内の参照がサポートされてます。
* *Created date column (作成日列)*​: この項目では、次の列のデータ型を使用できます。
** DATE
** DATETIME
** TIMESTAMP
** TIMESTAMP_NTZ

On New Or Updated Row::

15 秒ごとにウォーターマークの最大値 (​*[Created date column (作成日列)]*​ と ​*[Last modified date column (最終更新日列)]*​ の間) に基づいてテーブルのすべての新しい行または更新された行を返します。 
+
新しい行または更新された行のウォーターマーク値がウォーターマークの最大値よりも小さい場合、新しい行または更新された行は破棄されます。新しい行または更新された行のウォーターマーク値がウォーターマークの最大値よりも大きい場合、新しい行または更新された行が選択され、そのウォーターマークが新しい最大値に設定されます。 
+
フローが手動で非アクティブ化されて再アクティブ化されると、ウォーターマークはフローの開始時刻にリセットされます。フローで開始時刻が指定されていない場合、コンポーザーはフローがアクティブ化された時刻をタイムスタンプとして使用します。
+
次の項目の値を指定します。

* *Table (テーブル)*​: このトリガーでは、​*[Table (テーブル)]*​ 項目内の参照がサポートされてます。
* *Created date column (作成日列)*​: この項目では、次の列のデータ型を使用できます。
** DATE
** DATETIME
** TIMESTAMP
** TIMESTAMP_NTZ
* *Last modified date column (最終更新日列)*​: この項目では、次の列のデータ型を使用できます。
** DATE
** DATETIME
** TIMESTAMP
** TIMESTAMP_NTZ

== Actions (アクション)

include::_partials/action-definition.adoc[]

Insert Rows::

1 つ以上の行をテーブルに挿入してテーブルを更新します。​*[Query (クエリ)]*​ の値を指定します。

Update Rows::

行のセットを更新します。​*[Query (クエリ)]*​ の値を指定します。

Delete Rows::

行のセットを削除します。​*[Query (クエリ)]*​ の値を指定します。

Select Rows::

行のセットを取得します。​*[Query (クエリ)]*​ の値を指定します。

include::_partials/see-also.adoc[]
