ifeval::["​{product}​"=="salesforce"]
= MuleSoft Composer for Salesforce の用語集
endif::[]

ifeval::["​{product}​"=="mulesoft"]
= MuleSoft Composer の用語集
endif::[]

アクティブ化:: フローを開始するプロセス。

複製:: フロー全体 (すべてのアクションおよびトリガを含む) をコピーするプロセス。

接続:: データにアクセスするシステムへのアクセス権を付与するログイン情報 (ユーザ名とパスワード、およびアクセス権を取得するためにそれらを入力する URL)。一部のシステムでは、セキュリティトークンなどの追加情報が必要になります。

コピー:: フローの一部を複製するプロセス。レコード、トリガ、アクションをコピーできます。

//custom expression::

データピル:: フロー内から項目名や他のデータ構造を参照できるようにする変数。

データ構造:: データをシステムに保存する構造。たとえば、Salesforce では sObject および項目にデータが保存され、Google スプレッドシートではシート、行、セルに情報が保存されます。

編集:: 既存のフロー、アクション、またはトリガを変更するプロセス。

//field::

各:: 満たされた各トリガ条件のアクションを指定できるロジックオプション。

フロー:: システムに接続し、システムのデータに対してアクションを実行する自動化プロセス。

* *アクション*​: 接続からフェッチされたデータに対して行う操作 (システム間のレコードまたは行のコピーなど)。
* *ステップ*​: トリガ (1 つ以上のアクション)。ステップには、ステップを実行するのか、スキップするのかを決定するために必要なロジックが含まれます。必要に応じて、ステップに最初のトリガとは異なる接続を含めることもできます。
* *トリガ*​: すべてのフローの最初のステップ。トリガは、フローで定義された自動化プロセスを開始するものです。トリガは、「新規レコードの作成」などのイベントか、指定された時点になります。時間ベースのトリガは、スケジューラと呼ばれます。すべてのフローの最初のステップはトリガです。

if/else:: 条件を設定し、特定の条件を満たした場合にのみアクションを実行できるロジックオプション。これにより、複数の線形分岐をカバーするフローを作成できるようになり、個別のフローを作成する必要がなくなります。

ロジック:: アクションが実行される前に満たす必要のある状況または要件 (if/else ステートメントまたは for-each ステートメント)。必要に応じてロジックをステップに挿入し、返されるすべてのデータではなく、必要なデータに対してのみアクションが実行されるようにします。

監視:: 正常に実行されるようにアクティブ化されたフローを確認するプロセス。

//object type::

レコード:: コンポーザの項目およびデータ型のコレクション。  フローは、スケジュールに基づいて、またはレコードの変更の結果としてトリガされます。その後、そのレコードはフローの各ステップで処理されます。

修正:: OAuth 接続を再接続するためにアクセストークンを更新するアクション。

//sample type::

schedule (スケジュール):: 一定間隔でのフローの開始を自動化するプロセス。

スケジューラ:: フローがスケジュールされるメカニズム。

システム:: コンポーザは、Salesforce、NetSuite、Google スプレッドシートなどのシステムに接続し、フローとして構築、テスト、アクティブ化する自動化プロセスを実行します。システムへの接続は、フローの任意のステップで作成できます。システムがコンポーネントがホストされている Salesforce 組織と同じであっても、フローは最初のステップ、トリガまたはスケジューラでシステムに接続する必要があります。

タスク:: Composer for Salesforce によってインテグレーションフローの対象システムのオブジェクトまたはレコードに行われた変更 (挿入、更新、削除)。

テスト:: フローの作成時にトリガやアクションが適切に機能することを確認するために使用されるプロセス。

include::_partials/see-also.adoc[]
