= Google Sheets Connector リファレンス

Google スプレッドシートをデータ取得元として使用するか (例: 新しい Google スプレッドシート行を取得し、行の情報が含まれる Slack メッセージを送信する)、データ取得先として使用します (例: 新しい Salesforce 取引先責任者を取得し、Google スプレッドシートの行に変換する)。
フローのデータの操作方法のいくつかの詳細は、データ取得元またはデータ取得先に固有です。また、選択した特定のトリガまたはアクションに応じて変わります。

== Connections (接続)

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
コンポーザは、コンポーザに接続する Google ドライブアカウントを選択する認証ダイアログを起動します。まだログインしていない場合は、ユーザ名とパスワードを入力します。

== トリガ

include::_partials/trigger-definition.adoc[]

New spreadsheet::

このトリガは、接続に関連付けられた Google ドライブで新しいスプレッドシートが作成されたときに起動します。
+
Google スプレッドシートは作成時には保存されず、初めて編集されたときに保存されます。そのため、新しいスプレッドシートが作成されても、そのスプレッドシートが編集され、保存されるまでフローはトリガされません。ただし、保存日は最初に編集されたタイミングではなく作成されたタイミングになります。そのため、2 番目のスプレッドシートを作成し、最初のスプレッドシートを編集する前に編集すると、2 番目のスプレッドシートでフローがトリガされ、最初のスプレッドシートは無視されます。

New row in sheet::

スプレッドシート内の 1 つのシートを監視し、シートの最後に新しい行が追加されたときにトリガします。フローが開始されると、このトリガはシートのすべての既存の行を返します。その後、フローがトリガされるたびに、シートに追加された新しい行が返されます。
+
テキストが 1 つのセルまたは列に存在する場合、これらのセルまたは列を更新しても、新しい行としてトリガされません。セルまたは列を更新したときに新しい行をトリガするには、​*Update row in sheet*​ トリガを使用します。

Updated row in sheet::

スプレッドシート内の 1 つのシートを監視し、行が作成または更新されたときにトリガします。フローが開始されると、このトリガはシートのすべての既存の行を返します。その後、フローがトリガされるたびに、シートの新しい行または更新された行が返されます。

=== 制限

* シートは 10,000 行に制限される
* ヘッダー行は除外される
* トリガはチームドライブではなくマイドライブで機能する

== アクション

include::_partials/action-definition.adoc[]

Create row::

このアクションは、接続に名前が記載されているシートの最後に新しい行を追加します。

Update row::

このアクションは、シートの行を更新します。

=== 制限

* Google スプレッドシートにはヘッダー行が必要です。データが 1 行目に保存される場合、そのアクションは失敗します。
* 複合データピルに null または空の値があると、Google スプレッドシートでセルへの書き込みは行われません。これは、​*Update row*​ または ​*Create row*​ アクションに影響する可能性があります。

*Google スプレッドシート™ は Google LLC の商標です。*​

include::_partials/see-also.adoc[]
