= テンプレートを使用したフローのビルド

テンプレートから新しいフローを作成できます。

テンプレートは、フローをビルドするために活用できるパターンです。すべてのステップと項目のマッピングは事前に定義されているため、テンプレートを選択し、使用されるさまざまなコネクタの不足情報 (接続シークレットなど) を入力して、後でビジネスニーズに合わせてカスタマイズ可能なフローを作成できます。たとえば、接続に固有の必須項目を追加したり、追加の項目をマップしたり、ユースケースに合わせてステップを追加または削除したりする必要がある場合があります。多くの場合、フローを有効化する前にいくつかの変更を行う必要があります。

テンプレートは事前ビルド済みのフローであるため、アクセスに対する壁が低く、フローをアクティブ化するまでの時間が短縮されるだけでなく、フローのベストプラクティスも含まれています。

テンプレートの例を次に示します。

* Service Cloud や Revenue Cloud などのクラウド固有のテンプレート
* Salesforce、ServiceNow、NetSuite、Jira などのコネクタ固有のテンプレート

テンプレートから新しいフローを作成する方法についての詳細は、​xref:ms_composer_flows.adoc#create-a-new-flow-from-template[「テンプレートから新しいフローを作成する」]​を参照してください。

== テンプレートのカスタマイズ

テンプレートからフローをさらにカスタマイズする必要がある可能性が高いため、テンプレートからフローをカスタマイズしているときにメッセージが表示された場合は、次の推奨事項とガイドラインを考慮してください。

=== インスタンスには異なる項目が必要

インスタンスにテンプレートとは異なる項目が含まれている可能性があります。たとえば、使用されていない必須項目の追加、または接続に存在しないテンプレートで使用されている項目の削除が必要な場合があります。これらのエラーは、フローをテストする前に解決する必要があります。

=== 接続に項目が存在しない

接続に入力項目が存在しない場合、​`「This field does not exist with your connection (この項目は接続に存在しません)」`​というメッセージが表示されます。たとえば、前提条件で定義されたカスタム項目を作成する場合、テンプレートに保存されたカスタム項目の ID とインスタンスで作成されたカスタム項目の ID は (名前は同じでも) 異なるため、フローでエラーが発生します。テンプレートに保存されたカスタム項目を削除してから、項目セレクタからカスタム項目を再度追加できます。

=== 接続に値が存在しない

接続に出力項目 (データピル) が存在しない場合、​`「This value does not exist with your connection (この値は接続に存在しません)」`​というメッセージが表示されます。たとえば、前提条件で定義されたカスタム項目を作成する場合、テンプレートに保存されたカスタム項目の ID とインスタンスで作成されたカスタム項目の ID は (名前は同じでも) 異なるため、フローでエラーが発生します。マップされたデータピルを削除して、ドロップダウンからカスタム項目を選択できます。

include::_partials/see-also.adoc[]
