= Slack Connector リファレンス

Slack をデータ取得先として使用します。たとえば、Salesforce 商談が成立したときに Slack メッセージを送信できます。
フローでのデータの操作方法の一部の詳細は、このシステム、および選択したアクションに固有です。

== Connections (接続)

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name (ワークスペース名)::

Slack ワークスペース名 (例: `my-workspace.slack.com`​)。

ユーザ名とパスワード::

Slack にログインするために使用するユーザ名とパスワード。

== トリガ

スケジューラを使用して、フローがトリガされるタイミング (15 分ごとなど) を指定します。

Slack への接続を使用してフローをトリガすることはできません。

== アクション

include::_partials/action-definition.adoc[]

ダイレクトメッセージをユーザに送信します。::

指定されたユーザへのダイレクトメッセージを投稿するには、次の情報を指定します。
+
* *User (ユーザ)*​: メッセージを受信するユーザの ID。
* *Message (メッセージ)*​: 送信するメッセージ。複数のオプションから選択できます。
    ** テキストを入力する。
    ** データピルを選択する。
    ** *[Custom Expression (カスタム式)]*​ を選択してテキストとデータピルの任意の組み合わせを追加する。
* *Bot Name (ボット名)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ です。このアクションで送信されるメッセージについて、ここで別の名前を指定できます。
* *Bot Icon URL (ボットアイコン URL)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ であり、アイコンフォームに MuleSoft ロゴが含まれます。このアクションで送信されるメッセージについて別のアイコンを指定できます。|アクセス権が制限されていないアイコンの URL を指定します。

Create a message::

新規メッセージを選択した特定の非公開または公開チャネルに投稿します。メッセージ非公開チャネルに投稿するには、最初に MuleSoft プラットフォームアプリケーションをその非公開チャネルに追加する必要があります。
+
* *Channel Name (チャネル名)*​: 既存のチャネルのドロップダウンリストから選択する Slack ワークスペースのチャネル。
* *Message (メッセージ)*​: 送信するメッセージ。複数のオプションから選択できます。
    ** テキストを入力する。
    ** データピルを選択する。
    ** *[Custom Expression (カスタム式)]*​ を選択してテキストとデータピルの任意の組み合わせを追加する。
* *Bot Name (ボット名)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ です。このアクションで送信されるメッセージについて別の名前を指定できます。
* *Bot Icon URL (ボットアイコン URL)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ であり、アイコンフォームに MuleSoft ロゴが含まれます。このアクションで送信されるメッセージについて別のアイコンを指定できます。|アクセス権が制限されていないアイコンの URL を指定します。

Get user by email address::

*[Email (メール)]*​ 項目にメールアドレスを入力して Slack ユーザを検索します。
+
ユーザの ID を動的に取得するには、このアクションを挿入すれば、別のシステムからメールアドレスによって Slack ユーザが取得されます。このアクションで返された ​*[ID]*​ データピルを使用して、メッセージを受信するユーザを指定します。

include::_partials/see-also.adoc[]
