= Workday Connector リファレンス

Workday をデータ取得元またはデータ取得先として使用します。
フローでのデータの操作方法の一部の詳細は、データ取得元またはデータ取得先、および選択した特定のトリガーまたはアクションに固有です。

== Connections (接続)

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]
+
接続を検証およびテストするために、Workday Connector は ​`Get_Degrees`​ 操作で ​`Performance_Management`​ サービスを使用します。そのサービスで操作を実行する権限がサービスアカウントにあることを確認してください。
+
[%header%autowidth.spread]
|===
|セキュリティポリシー|ドメイン/機能エリア|許可されたセキュリティグループ
|セットアップ: スキルと経験 |ワーカープロファイルとスキル a| * HR 管理者
* HR システム
* 実装者
* 職務および役職管理者
* 学習管理システム
| |実装| 実装者
|特殊 OX Web サービス|実装|
|===

Tenant Name (テナント名)::

Workday テナントの名前または ID。
+
たとえば、Workday にログインする URL が ​`na.workday.com/wday/authgwy/global-modern/`​ の場合、テナント名は ​`global-modern`​ になります。
+
Sandbox からテナント名を取得する手順は、次のとおりです。

. ページの左上を確認します。そこにテナントの詳細が​`「Sandbox 種別- テナント名」`​の形式で表示されています。

User Name (ユーザー名)::

Workday にログインするために使用するユーザー名。

Password (パスワード)::

Workday にログインするために使用するパスワード。

Host Name (ホスト名)::

Workday インスタンスのホスト名。例: `wd2-impl-services1.workday.com`​。
+
ホスト名を見つける手順は、次のとおりです。

. Web インターフェースから Workday にログインします。
. 検索ボックスに​`「Public Web Service」`​ (公開 Web サービス) と入力し、検索結果から ​*[Public Web Service (公開 Web サービス)]*​ を選択します。
. *[...]*​ をクリックし、​*[Web Service (Web サービス)] > [View WSDL (WSDL を表示)]*​ を選択します。​`soapbind:address`​ をチェックして、正しいホスト名 (例: `<soapbind:address location=”https://hostname/ccx/.... />`​) を使用していることを確認します。 

== トリガー

include::_partials/trigger-definition.adoc[]

New or updated object::

このトリガーでは、Workday 財務管理で新規または更新済みオブジェクトをチェックします。次の項目では値が必須です: *Object (オブジェクト)*​。

=== Polling Frequency (ポーリング頻度) 

include::_partials/polling-frequency.adoc[]

== アクション

include::_partials/action-definition.adoc[]

Get Worker Details by ID::

このアクションでは、指定した従業員の ​`Workday ID`​ に対応するワーカーの詳細を返します。

Create Worker::

このアクションでは、新しいワーカーを作成します。

Update Job Requisition::

このアクションでは、ジョブの必要条件に関する詳細を更新します。

Get Customer::

このアクションでは、指定した顧客 ID に対応する顧客の詳細を返します。

Create Object::

このアクションでは、Workday 財務管理で新しいオブジェクトを作成します。​*[Object (オブジェクト)]*​ の値を指定します。

Update Object (オブジェクトを更新)::

このアクションでは、Workday 財務管理で既存のオブジェクトを更新します。次の項目の値を指定します。

* *Object*
* *Unique ID (一意の ID)*

Get Object::

このアクションでは、Workday 財務管理で既存のオブジェクトを返します。次の項目の値を指定します。

* *Object*
* *ID*

== Object Types (オブジェクト種別)

次のオブジェクト種別が使用できます。

* トリガー
    ** JOB_REQUISITIONS
    ** WORKER

* アクション
    ** COMPANY
    ** CONTRACT
    ** CUSTOMER
    ** INVOICE
    ** JOB_REQUISITIONS
    ** PROJECT
    ** SALES_ITEM
    ** WORKER

== カスタム項目 

カスタム項目はサポートされていません。MuleSoft Composer を使用して、Workday レコードで設定したアクションとトリガーのカスタム項目値にアクセスできます。

include::_partials/see-also.adoc[]
