= Salesforce Marketing Cloud Connector リファレンス

Salesforce Marketing Cloud は、リアルタイム顧客エンゲージメント、メールとマーケティングの自動化、ソーシャルメディアエンゲージメント、モバイル (SMS) メッセージングとプッシュ通知、顧客マーケティング分析などの機能をサポートするマーケティングプラットフォームです。

== 接続

システムに接続するには、それがデータの取得元であるかデータの取得先であるかに関係なく、そのシステムに必要なログイン情報を使用して接続を作成する必要があります。通常、フロー内の異なるシステムに接続し、接続が必要になるたびに各接続を再利用できます。

インストール済みパッケージで API インテグレーションを作成する方法についての詳細は、 https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/integration-s2s-client-credentials.html[「Server-to-Server Integrations with Client Credentials Grant Type (クライアントログイン情報許可種別を使用したサーバ間インテグレーション)」]​を参照してください。

このシステムでは、接続のために次のログイン情報が必要です。

Connection Display Name (接続表示名)::

この接続の詳細を把握するのに役立つ接続名を入力します。
1 つのフローおよび複数のフローで接続を複数回再利用できます。接続の作成後、ログイン情報は非表示になります。そのため、この接続を他の接続と簡単に区別できる名前を付けると役立ちます。
+
接続は自分にのみ表示されます。コンポーザアプリケーションの他のユーザは、独自の接続を作成する必要があります。

Client ID (クライアント ID)::

インストール済みパッケージからクライアント ID を入力します。

Client Secret (クライアントシークレット)::

インストール済みパッケージからクライアントシークレットを入力します。

Authentication URI (認証 URI)::

インストール済みパッケージから認証ベース URI を入力します。

Scopes (スコープ)::

(省略可能) MuleSoft Composer がアクセスできるスコープを入力します。これは、パッケージがここで必要な数以上のスコープにアクセスできる場合に役に立ちます。
必要となる最小スコープ: offline、email_send、sms_send、list_and_subscribers_read

== アクション

include::_partials/action-definition.adoc[]

Send email::

特定のテンプレートを使用して顧客にメールを送信します。次の項目の値を指定します。

* Email Definition (メール定義)
* Contact Key (連絡先キー)
* Email (メール)

Send SMS (SMS を送信)::

特定のテンプレートを使用して顧客に SMS を送信します。次の項目の値を指定します。

* SMS 定義
* Contact Key (連絡先キー)
* Recipient’s Phone Number (受信者の電話番号)

include::_partials/see-also.adoc[]
