= Slack Connector リファレンス

Slack をデータ取得元またはデータ取得先として使用します。たとえば、Salesforce 商談が成立したときに Slack メッセージを送信できます。
フローでのデータの操作方法の一部の詳細は、このシステム、および選択したアクションに固有です。

== Connections (接続)

include::_partials/connection-definition.adoc[]

include::_partials/connection-name.adoc[]

Workspace Name (ワークスペース名)::

Slack ワークスペース名 (例: `my-workspace.slack.com`​)。

ユーザ名とパスワード::

Slack にログインするために使用するユーザ名とパスワード。

== トリガ

include::_partials/trigger-definition.adoc[]

On New Message (新規メッセージ)::

このトリガが起動すると、後続のステップで新しいメッセージを使用できるようになります。

== アクション

include::_partials/action-definition.adoc[]

Send a direct message to a user::

指定されたユーザへのダイレクトメッセージを投稿するには、次の情報を指定します。
+
* *User (ユーザ)*​: メッセージを受信するユーザの ID。
* *Message (メッセージ)*​: 送信するメッセージ。複数のオプションから選択できます。
    ** テキストを入力する。
    ** データピルを選択する。
    ** *[Custom Expression (カスタム式)]*​ を選択してテキストとデータピルの任意の組み合わせを追加する。
* *Bot Name (ボット名)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ です。このアクションで送信されるメッセージについて、ここで別の名前を指定できます。
* *Bot Icon URL (ボットアイコン URL)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ であり、アイコンフォームに MuleSoft ロゴが含まれます。このアクションで送信されるメッセージについて別のアイコンを指定できます。|アクセス権が制限されていないアイコンの URL を指定します。

Post message to channel::

新規メッセージを選択した特定の非公開または公開チャネルに投稿します。メッセージ非公開チャネルに投稿するには、最初に MuleSoft プラットフォームアプリケーションをその非公開チャネルに追加する必要があります。
+
* *Channel Name (チャネル名)*​: 既存のチャネルのドロップダウンリストから選択する Slack ワークスペースのチャネル。
* *Message (メッセージ)*​: 送信するメッセージ。複数のオプションから選択できます。
    ** テキストを入力する。
    ** データピルを選択する。
    ** *[Custom Expression (カスタム式)]*​ を選択してテキストとデータピルの任意の組み合わせを追加する。
* *Bot Name (ボット名)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ です。このアクションで送信されるメッセージについて別の名前を指定できます。
* *Bot Icon URL (ボットアイコン URL)*​: デフォルトでは、アクションによって生成される Slack メッセージの送信者は ​*[MuleSoft Composer]*​ であり、アイコンフォームに MuleSoft ロゴが含まれます。このアクションで送信されるメッセージについて別のアイコンを指定できます。|アクセス権が制限されていないアイコンの URL を指定します。

Get user by email::

*[Email (メール)]*​ 項目にメールアドレスを入力して Slack ユーザを検索します。
+
ユーザの ID を動的に取得するには、このアクションを挿入すれば、別のシステムからメールアドレスによって Slack ユーザが取得されます。このアクションで返された ​*[ID]*​ データピルを使用して、メッセージを受信するユーザを指定します。

Add users to channel::

ユーザをチャネルに招待します。このアクションには新しい接続が必要です。次の項目の値を指定します。
+
* *Channel Name (チャネル名)*​: 既存のチャネルのドロップダウンリストから選択する Slack ワークスペースのチャネル。
* *User IDs (ユーザ ID)*​: チャネルに追加するユーザの ID。

Create channel::

公開または非公開チャネルベースの会話を作成します。このアクションには新しい接続が必要です。次の項目の値を指定します。
+
* *Name (名前)*​: 作成するチャネルの名前。
* *Is Private (非公開)*​: 作成するチャネルが非公開か公開かを決定します。
* *Team Id (チーム ID)*​: チャネルを作成するチームのエンコードされた ID。組織トークンを使用する場合、この ID は必須です。

Send direct message to multiple users::

複数ユーザのダイレクトメッセージチャネルにダイレクトメッセージを送信します。次の項目の値を指定します。
+
* *Channel Name (チャネル名)*​: 既存のチャネルのドロップダウンリストから選択する Slack ワークスペースのチャネル。
* *Attachments (添付ファイル)*​: メッセージのコンテンツに対する少なくとも 1 つの添付ファイル。
* *Blocks (ブロック)*​: メッセージのコンテンツに対する少なくとも 1 つのブロック。
* *Text (テキスト)*​: メッセージのコンテンツに対する少なくとも 1 つのテキスト引数。
* *Icon Emoji (アイコン絵文字)*​: メッセージのアイコンとして使用する絵文字。​*[Icon Url (アイコン URL)]*​ を上書きします。 
* *Icon Url (アイコン URL)*​: メッセージのアイコンとして使用する画像の URL。
* *Link Names (リンク名)*​: ユーザグループを検索してリンクします。 
* *Metadata (メタデータ)*​: URL エンコードされた文字列として表される JSON オブジェクト。
* *Mrkdwn*​: この項目を ​`false`​ に設定して、Slack マークアップ解析を無効にします。
* *Parse (解析)*​: メッセージの解析方法を変更します。
* *Reply broadcast (返信ブロードキャスト)*​: 返信がチャネルまたは会話の全員に表示されるかどうかを示します。​*[Thread ts (スレッド ts)]*​ と組み合わせて使用されます。
* *Thread ts (スレッド ts)*​: 別のメッセージの ts 値を指定して、このメッセージを返信にします。返信の ts 値の使用を避け、代わりにその親の ts 値を使用します。
* *Unfurl links (リンクを展開)*​: この項目を ​`true`​ に設定すると、主にテキストベースのコンテンツの展開が有効になります。
* *Unfurl media (メディアを展開)*​: この項目を ​`true`​ に設定すると、メディアコンテンツの展開が有効になります。
* *Username (ユーザ名)*​: ボットのユーザ名を設定します。 

//Post message to channel::

//When a message is posted to a channel, you can specify a list of attachments to include in the message.

//Sent a direct message to a user::

//When a direct message is sent, you can specify a list of attachments to include in the message.

include::_partials/see-also.adoc[]
