= Box Connector リファレンス

Box は、汎用の SaaS エンタープライズコンテンツ管理システムです。組織は Box を使用して、ドキュメント、画像、ビデオ、その他のさまざまなファイルを安全に管理し、コラボレーションします。

== Connections (接続)

include:composer::_partials/connection-definition.adoc[]

include:composer::_partials/connection-name.adoc[]

Username (ユーザー名)::

Box にログインするために使用する OAuth ユーザー名。

Password (パスワード)::

Box にログインするために使用する OAuth パスワード。

include:composer::_partials/binary-data.adoc[]

== トリガー

include:composer::_partials/trigger-definition.adoc[]

On new file in folder (フォルダー内の新しいファイル)::

新規フォルダーが追加されたときにトリガーされます。​*[Folder ID (フォルダー ID)]*​ の値を指定します。

=== Polling Frequency (ポーリング頻度) 

include:composer::_partials/polling-frequency.adoc[]

== アクション

include:composer::_partials/action-definition.adoc[]

Add file to folder using URL (URL を使用してフォルダーにファイルを追加)::

公開され共有されていいる URL で参照される Box のフォルダーにファイルを追加します。次の項目の値を指定します。

* *Folder ID (フォルダー ID)*
* *Source URL (ソース URL)*

Upload File::

Box のフォルダーにファイルを追加します。次の項目の値を指定します。

* *File Name (ファイル名)*
* *File contents (ファイルコンテンツ)*
* *Folder ID (フォルダー ID)*
* *Existing File ID (既存のファイル ID)*

Download file (ファイルをダウンロード)::

指定されたファイルとバージョンのバイナリコンテンツを返します。次の項目の値を指定します。

* *File ID (ファイル ID)*
* *Version (バージョン)*

Create folder (フォルダーの作成)::

Box 構造内にフォルダーを作成します。次の項目の値を指定します。

* *Parent Folder ID (親フォルダー ID)*
* *Folder name (フォルダー名)*

Create file metadata (ファイルメタデータの作成)::

Box のファイルにメタデータテンプレートを入力して、ファイルメタデータを作成します。次の項目の値を指定します。

* *File ID (ファイル ID)*
* *Metadata template (メタデータテンプレート)*

+
チェックボックスなどの複数選択項目のデータ型は、コンポーザーには表示されません。

Update file metadata (ファイルのメタデータの更新)::

Box のファイルに対する既存のメタデータテンプレートを更新することで、ファイルのメタデータを更新します。次の項目の値を指定します。

* *File ID (ファイル ID)*
* *Metadata template (メタデータテンプレート)*

+
チェックボックスなどの複数選択項目のデータ型は、コンポーザーには表示されません。

include:composer::_partials/see-also.adoc[]
